# Detecting Confidence in Management via Earnings Call

## Problem Statement

In [ ]:
# !pip install datasets
!pip install scikit-optimize
!pip install optuna

In [2]:
import torch
from torch import nn
# from transformers import BertTokenizer, Trainer, BertForSequenceClassification, TrainingArguments, AdamW, get_linear_schedule_with_warmup
from transformers import BertTokenizer, Trainer, BertForSequenceClassification, TrainingArguments, get_linear_schedule_with_warmup
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from tqdm import tqdm
import numpy as np
# from datasets import Dataset
from sklearn.metrics import accuracy_score
# import scikit-optimize as skopt
from skopt import gp_minimize
from skopt.space import Real
import optuna
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

In [3]:
torch.manual_seed(42)

# Set device (GPU if available, else CPU)
device = (
    "mps"
    if torch.backends.mps.is_available()
    else "cuda"
    if torch.cuda.is_available()
    else "cpu"
)
device = torch.device(device)
print(f"Using device: {device}")

Using device: cpu

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

My aim is to classify each sentence spoken by the management of a company during the earnings call into the following categories:
- **Confident**: Clear, assertive statements with no hedging (e.g., "We are certain that our strategy will deliver strong growth").    
- **Neutral**: Factual or descriptive statements with little to no sentiment (e.g., "Revenue increased by 10% in Q3").  
- **Uncertain**: Statements that are heavily qualified, ambiguous, or indicate significant doubt (e.g., "It is unclear whether we can meet our targets").

I extract the spoken words by the management only, because they are the representatives of the company, and analysing their confidence levels in their speech would be insightful for investors' risk assessment. According to the paper (["Assessing the Predictive Power of Earnings Call Transcripts on Next-Day Stock Price Movement: A Semantic Analysis Using Large Language Models"](https://www.ischool.berkeley.edu/projects/2024/assessing-predictive-power-earnings-call-transcripts-next-day-stock-price-movement)), manangement's tone and guidance can be insightful for stock price prediction.

I decide to use pre-trained FINBERT for fine-tuning, as it is already pre-trained on financial texts, including 1.3B tokens of earnings-call transcripts. Hence, FINBERT should already be very well trained and familiar with sentences in earnings calls, making my fine-tuning work more effective.

It is very common to see FINBERT fine tuned on texts like news and social media content for sentiment analysis. To the best of my knowledge, fine tuning FINBERT on confidence is more rare. Hence, I decide to focus on managements' confidence levels during earnings call, which may signifiy the prospects of the company.

## Data Sourcing, Cleaning & Preprocessing

Dataset: https://www.kaggle.com/datasets/ashwinm500/earnings-call-transcripts
188 earnings call transcripts, from 10 NASDAQ companies

Below, I use regex to extract the words spoke by management only, and store them as sentences in a dataframe.

In [5]:
# REGEX Code to extract spoken words by management only (based on the names in corporate participants)

import re
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize

# Download NLTK sentence tokenizer (only needed once)
nltk.download("punkt_tab")

def process_transcript(file_path):
    # Load the earnings call transcript from a text file
    with open(file_path, "r", encoding="utf-8") as file:
        transcript = file.read()

    # Step 1: Extract Management Participants
    management_section = re.search(r"Corporate Participants\s*=+\n(.*?)\n=+", transcript, re.DOTALL)

    if management_section:
        management_text = management_section.group(1)
        management_names = re.findall(r"\*\s+(.+)", management_text)  # Extract names after "*"
    else:
        print("Could not find Corporate Participants section.")
        exit()

    # Step 2: Extract Spoken Words of Each Management Member
    management_sentences = []

    for person in management_names:
        pattern = rf"(?<=--------------------------------------------------------------------------------\n){person}.*?\n-+\n(.*?)(?=\n\n-+|\n\n=+|\Z)"
        matches = re.findall(pattern, transcript, re.DOTALL)

        if matches:
            spoken_text = " ".join(matches).strip()

            # Step 3: Tokenize into sentences
            sentences = sent_tokenize(spoken_text)
            management_sentences.extend(sentences)  # Add to final list

    # Step 4: Convert into a Pandas DataFrame
    df = pd.DataFrame(management_sentences, columns=["Sentence"])
    return df

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

I only choose to select two transcripts from each company, which would give me around 6000 data points (each data point = 1 sentence), and according to [link](https://www.linkedin.com/pulse/how-many-data-points-necessary-fine-tuning-model-premai-tqc3f/), 6000 should be sufficient to give decent results.

In [6]:
import os
import fnmatch
root_directory = '/content/drive/My Drive/DSA4265/Transcripts' # Change this accordingly

# Store all the file paths for all the earnings call transcripts
all_files = []
for dirpath, dirnames, filenames in os.walk(root_directory):
    lst = []
    for filename in fnmatch.filter(filenames, '*.txt'):
        file_path = os.path.join(dirpath, filename)
        lst.append(file_path)
    all_files.append(lst)


# Select two transcripts from each company for computational efficiency
df_all = pd.DataFrame()
for lst in all_files:
    if not lst:
        continue
    else:
        df_all = pd.concat([df_all, process_transcript(lst[-1]), process_transcript(lst[-2])], axis=0)

df_all = df_all.reset_index(drop=True)

In [7]:
df_all

                                               Sentence
0     Thank you, Karen, and welcome to Micron Techno...
1     On the call with me today are Sanjay Mehrotra,...
2     This conference call, including audio and slid...
3     In addition, our website contains the earnings...
4     The prepared remarks from today's call will al...
...                                                 ...
6689  All our statements are made as of today, Febru...
6690  Except as required by law, we assume no obliga...
6691  During this call, we will discuss non-GAAP fin...
6692  You can find a reconciliation of these non-GAA...
6693   With that, let me turn the call over to Colette.

[6694 rows x 1 columns]

Note that I don't remove stopwords, don't perform lemmatization and don't convert all letters to lower case, as BERT is case sensitive, and removing/modifying words may hinder BERT's ability to understand the whole context of the sentence.

I simply remove uninformative sentences, such as "Thank you Ivan", "I shall pass my time to Jensen." etc.

However, it is very difficult to perfectly remove all uninformative sentences. I remove them based on the presence of common phrases like "Thank you", "I will now pass" etc. It is possible that there are other uninformative sentences that we miss out. Due to the constraints of time, we are unable to manually go through every sentences.

In [8]:
# Remove uninformative sentences
import re

def is_informative(sentence):
    transition_phrases = [
        "thank you", "i will now pass", "i shall now pass", "let’s move on",
        "i would like to hand over", "please go ahead", "any questions", "thank you for your time",
        "turn the call over", "operator", "thanks", "disconnect"
    ]
    if any(phrase in sentence.lower() for phrase in transition_phrases):
        return False

    # Remove sentences that are only numbers/symbols
    if re.fullmatch(r"[\W\d]+", sentence):
        return False

    return True

df = df_all[df_all["Sentence"].apply(is_informative)]

I remove any trailing/leading or extra white spaces in the sentences to ensure uniformity.

In [9]:
# Removes unwanted whitespace characters
df.loc[:, "Sentence"] = df["Sentence"].str.replace(r"\s+", " ", regex=True).str.strip()

I also remove extremely short sentences. I choose to remove sentences with < 10 words, as they typically lack context. It is a difficult threshold to determine. There exist some short sentences like "Certainly, it can be", which may seem to indicate confidence, but it can be an answer to a trivial, non-financial/business question. Similarly, I also risk deleting short sentences which may indeed indicate confidence about the company. However, I still decide to keep the threshold decently long at 10 words, as it is safer to eliminate false positives that may confuse the model.

In [10]:
# Remove very short sentences < 10 words
df = df[df["Sentence"].str.len() > 10]


df = df.reset_index(drop=True)

In [11]:
df

                                               Sentence
0     On the call with me today are Sanjay Mehrotra,...
1     This conference call, including audio and slid...
2     In addition, our website contains the earnings...
3     The prepared remarks from today's call will al...
4     Today's call will be approximately 60 minutes ...
...                                                 ...
6283  For a discussion of factors that could affect ...
6284  All our statements are made as of today, Febru...
6285  Except as required by law, we assume no obliga...
6286  During this call, we will discuss non-GAAP fin...
6287  You can find a reconciliation of these non-GAA...

[6288 rows x 1 columns]

## Data Labelling

Now, I label the dataset using Roberta. Since I have around 6000 rows, I cannot do manual labelling due to time constraints. There are several free-of-charge alterantives, such as using FLAN-T5, Distilbert.

However, after trying FLAN-T5, I discovered that is wasn't that fine-tuned to classify "confident", "uncertain" or "neutral" sentences, so it ended up classifying many neutral sentences as "confident".  

Roberta would be a better alternative to label the data, as it allows for a "Positive", "Negative" and "Neutral" nulti-classification unlike distilbert.

I then map "Positive" to "Confident", "Negative" to "Uncertain", and "Neutral" to itself for our use case. Although there might be subtle differences between "Positive" and "Confident", as positive doesn't always imply confidence, it is a compromise we make given time constraints. Ideally, one should manually label the sentences.

*If you do not want to run the labelling code, skip to next section to directly read in the already-labelled dataset*

In [ ]:
# pip install pandas torch transformers

In [ ]:
# Install necessary packages
# !pip install pandas torch transformers tqdm scipy

import pandas as pd
# import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import softmax
from tqdm import tqdm

# Load your dataset
# Ensure your DataFrame 'df' has a column named 'Sentence' containing the text to be analyzed
# For example, if loading from a CSV file:
# df = pd.read_csv('your_dataset.csv')

# Load the tokenizer and model
model_name = "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Define sentiment labels
labels = ['Negative', 'Neutral', 'Positive']

# Preprocess text (e.g., handle usernames and URLs)
def preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

# Function to classify sentiment
def classify_sentiment(text):
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt')
    output = model(**encoded_input)
    scores = output[0][0].detach().numpy()
    scores = softmax(scores)
    ranking = scores.argmax()
    return labels[ranking]

# Apply the function to the 'Sentence' column with a progress bar
tqdm.pandas(desc="Processing Sentences")
df['sentiment'] = df['Sentence'].progress_apply(classify_sentiment)

# Define your custom mapping
custom_mapping = {
    'Positive': 'Confident',
    'Neutral': 'Neutral',
    'Negative': 'Uncertain'
}

# Apply the mapping to the 'sentiment' column
df['custom_label'] = df['sentiment'].map(custom_mapping)

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.5.1+cu124)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.48.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (1.13.1)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2024.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.28.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 30.3 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 24.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 25.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.3 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.1 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 9.0 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.6 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 88.6 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Processing Sentences:   0%|          | 2/6278 [00:00<26:33,  3.94it/s]

model.safetensors:   0%|          | 0.00/501M [00:00<?, ?B/s]

Processing Sentences: 100%|██████████| 6278/6278 [14:57<00:00,  6.99it/s]

In [ ]:
# Drop the sentiment column, retain the custom label for our use case
df = df.drop(columns=['sentiment'])

In [ ]:
# A last minute added on data cleaning, found out that rows 2918 to 3227 had sentences that contains symbols

def remove_angle_brackets(text):
    # Use regular expression to remove text within angle brackets
    return re.sub(r'<.*?>', '', text).strip()
# Apply the function to the 'Sentence' column
df['Sentence'] = df['Sentence'].apply(remove_angle_brackets)

In [ ]:
# Create a mapping dictionary
label_map = {
    'Neutral': 0,
    'Confident': 1,
    'Uncertain': 2
}

# Apply the mapping to the 'label' column
df['custom_label'] = df['custom_label'].map(label_map)

In [ ]:
# Create a new data frame to switch the columns

df_new = pd.DataFrame(columns=['label', 'text'])

df_new['label'] = df['custom_label']
df_new['text'] = df['Sentence']

## Fine Tuning FINBERT

Uncomment the code directly below to read in the labelled data.

In [22]:
df_new = pd.read_csv('/content/drive/MyDrive/DSA4265/Assignment 1/final_labelled_data.csv')
df_new = df_new.drop(columns = ["Unnamed: 0"])

In [23]:
df_new

      label                                               text
0         0  On the call with me today are Sanjay Mehrotra,...
1         0  This conference call, including audio and slid...
2         0  In addition, our website contains the earnings...
3         0  The prepared remarks from today's call will al...
4         0  Today's call will be approximately 60 minutes ...
...     ...                                                ...
6273      0  For a discussion of factors that could affect ...
6274      0  All our statements are made as of today, Febru...
6275      0  Except as required by law, we assume no obliga...
6276      0  During this call, we will discuss non-GAAP fin...
6277      0  You can find a reconciliation of these non-GAA...

[6278 rows x 2 columns]

In [24]:
# Split data ensuring indices are reset
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df_new['text'].reset_index(drop=True),
    df_new['label'].reset_index(drop=True),
    test_size=0.2,
    random_state=42
)

The pretrained FinBERT model path on Huggingface is https://huggingface.co/yiyanghkust/finbert-pretrain

In [25]:
# Load finbert pre-trained model
model = BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-pretrain',num_labels=3)
tokenizer = BertTokenizer.from_pretrained('yiyanghkust/finbert-pretrain')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at yiyanghkust/finbert-pretrain and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Hyperparameter optimisation & Fine-tuning of Finbert**

In [26]:
# ---------------------- Custom Dataset ---------------------- #
class EarningsCallDataset(Dataset):
    """
    Custom dataset that tokenizes input texts and returns a dictionary
    with input_ids, attention_mask, and labels.
    """
    def __init__(self, texts, labels, tokenizer, max_length=128):
        # Convert to list if not already
        self.texts = texts.tolist() if hasattr(texts, 'tolist') else list(texts)
        self.labels = labels.tolist() if hasattr(labels, 'tolist') else list(labels)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        # Get the text and label at index idx and tokenize
        # print(idx)
        text = str(self.texts[idx])
        label = self.labels[idx]
        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,       # Add special tokens ([CLS], [SEP])
            max_length=self.max_length,
            return_token_type_ids=False,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'            # Return PyTorch tensors
        )
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

train_dataset = EarningsCallDataset(train_texts, train_labels, tokenizer)
val_dataset = EarningsCallDataset(val_texts, val_labels, tokenizer)

In [27]:
# ---------------------- Configuration ---------------------- #
def get_config():
    """
    Returns the default configuration dictionary.
    freeze_layers is True during hyperparameter tuning.
    gradual_unfreeze flag will be used during final fine-tuning.
    """
    return {
        "model_name": "yiyanghkust/finbert-pretrain",  # Pre-trained FinBERT model
        "num_labels": 3,                              # Number of labels for classification
        "max_length": 128,                            # Maximum token length
        "batch_size": 32,                             # Default batch size
        "learning_rate_bert": 2e-5,                     # Learning rate for BERT layers
        "learning_rate_classifier": 1e-3,             # Learning rate for classifier head
        "weight_decay": 0.01,                         # Weight decay
        "num_epochs": 3,                              # Number of fine-tuning epochs
        "freeze_layers": True,                        # Initially freeze BERT layers during tuning
        "gradual_unfreeze": True                      # Enable gradual unfreezing during final fine-tuning
    }


# ---------------------- Tokenizer ---------------------- #
# Initialize tokenizer from the pre-trained model.
tokenizer = BertTokenizer.from_pretrained(get_config()["model_name"])

# ---------------------- DataLoader Creation ---------------------- #
def create_dataloaders(batch_size):
    """
    Creates DataLoaders for training and validation.
    Assumes train_texts, train_labels, val_texts, and val_labels are defined.
    """
    train_dataset = EarningsCallDataset(train_texts, train_labels, tokenizer, max_length=get_config()["max_length"])
    val_dataset = EarningsCallDataset(val_texts, val_labels, tokenizer, max_length=get_config()["max_length"])
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    return train_loader, val_loader

# ---------------------- Model Initialization ---------------------- #
def initialize_model(config):
    """
    Initializes the BERT model for sequence classification.
    Moves the model to the available device.
    Freezes BERT layers if config["freeze_layers"] is True.
    Sets up AdamW optimizer with separate parameter groups.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = BertForSequenceClassification.from_pretrained(
        config["model_name"], num_labels=config["num_labels"]
    ).to(device)

    # Freeze BERT layers if needed
    if config["freeze_layers"]:
        for param in model.bert.parameters():
            param.requires_grad = False

    optimizer = AdamW([
        {'params': model.bert.parameters(), 'lr': config["learning_rate_bert"], 'weight_decay': config["weight_decay"]},
        {'params': model.classifier.parameters(), 'lr': config["learning_rate_classifier"], 'weight_decay': config["weight_decay"]}
    ])
    return model, optimizer, device

# ---------------------- Training Function ---------------------- #
def train_epoch(model, data_loader, optimizer, device):
    """
    Trains the model for one epoch.
    Returns training accuracy and average loss.
    """
    model.train()
    correct_predictions = 0
    losses = []
    for batch in tqdm(data_loader, desc="Training"):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = torch.nn.CrossEntropyLoss()(outputs.logits, labels)
        losses.append(loss.item())
        # Predictions
        _, preds = torch.max(outputs.logits, dim=1)
        correct_predictions += torch.sum(preds == labels)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

    accuracy = correct_predictions.double() / len(data_loader.dataset)
    return accuracy, np.mean(losses)

# ---------------------- Evaluation Function ---------------------- #
def eval_model(model, data_loader, device):
    """
    Evaluates the model on the validation set.
    Collects predictions and true labels to compute:
      - Accuracy
      - Average Loss
      - Precision, Recall, F1-Score (weighted average)
      - AUC (using one-vs-rest for multiclass)
    Returns these metrics.
    """
    model.eval()
    correct_predictions = 0
    losses = []
    all_labels = []
    all_preds = []
    all_probs = []

    with torch.no_grad():
        for batch in tqdm(data_loader, desc="Evaluating"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = torch.nn.CrossEntropyLoss()(outputs.logits, labels)
            losses.append(loss.item())

            # Get predicted labels
            _, preds = torch.max(outputs.logits, dim=1)
            correct_predictions += torch.sum(preds == labels)

            # Collect true labels and predictions
            all_labels.extend(labels.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())
            # Compute probabilities using softmax
            probs = torch.nn.functional.softmax(outputs.logits, dim=1)
            all_probs.extend(probs.cpu().numpy())

    accuracy = correct_predictions.double() / len(data_loader.dataset)
    avg_loss = np.mean(losses)

    # Convert lists to numpy arrays
    all_labels = np.array(all_labels)
    all_preds = np.array(all_preds)
    all_probs = np.array(all_probs)

    # Calculate precision, recall, and F1-score using weighted average
    precision = precision_score(all_labels, all_preds, average='weighted')
    recall = recall_score(all_labels, all_preds, average='weighted')
    f1 = f1_score(all_labels, all_preds, average='weighted')

    # For multiclass AUC, use one-vs-rest scheme; if AUC computation fails, set to None.
    try:
        auc = roc_auc_score(all_labels, all_probs, multi_class='ovr', average='weighted')
    except Exception as e:
        auc = None
        print("AUC computation failed:", e)

    return accuracy, avg_loss, precision, recall, f1, auc

# # ---------------------- Gradual Unfreezing ---------------------- #
# def gradual_unfreeze(model, current_epoch, total_epochs):
#     """
#     Gradually unfreezes the BERT encoder layers.
#     For a linear schedule, the number of layers to unfreeze is:
#       floor((current_epoch+1)/total_epochs * total_layers)
#     First, all layers are frozen, then the last 'N' layers are unfrozen.
#     Returns the number of layers that are unfrozen.
#     """
#     total_layers = len(model.bert.encoder.layer)
#     layers_to_unfreeze = int((current_epoch + 1) / total_epochs * total_layers)
#     layers_to_unfreeze = max(0, min(layers_to_unfreeze, total_layers))
#     # Freeze all layers
#     for layer in model.bert.encoder.layer:
#         for param in layer.parameters():
#             param.requires_grad = False
#     # Unfreeze the last 'layers_to_unfreeze' layers
#     if layers_to_unfreeze > 0:
#         for layer in model.bert.encoder.layer[-layers_to_unfreeze:]:
#             for param in layer.parameters():
#                 param.requires_grad = True
#     return layers_to_unfreeze

def gradual_unfreeze(model, current_epoch, total_epochs):
    """
    Gradually unfreezes the BERT encoder layers.
    For a linear schedule, the number of layers to unfreeze is:
      floor((current_epoch+1)/total_epochs * total_layers)
    First, all layers are frozen, then the last 'N' layers are unfrozen.
    Returns the number of layers that are unfrozen.
    """
    total_layers = len(model.bert.encoder.layer)
    layers_to_unfreeze = int((current_epoch + 1) / total_epochs * total_layers)
    layers_to_unfreeze = max(0, min(layers_to_unfreeze, total_layers))

    # Freeze all layers
    for layer in model.bert.encoder.layer:
        for param in layer.parameters():
            param.requires_grad = False

    # Unfreeze the last 'layers_to_unfreeze' layers
    if layers_to_unfreeze > 0:
        for layer in model.bert.encoder.layer[-layers_to_unfreeze:]:
            for param in layer.parameters():
                param.requires_grad = True

    return layers_to_unfreeze

# ---------------------- Hyperparameter Tuning ---------------------- #
def objective(trial):
    """
    Objective function for Bayesian optimization.
    Updates configuration with hyperparameters sampled by Optuna.
    Trains and evaluates the model for one epoch, returning validation loss.
    """
    config = get_config()
    config["learning_rate_bert"] = trial.suggest_loguniform("learning_rate_bert", 1e-6, 5e-5)
    config["learning_rate_classifier"] = trial.suggest_loguniform("learning_rate_classifier", 1e-5, 1e-2)
    config["weight_decay"] = trial.suggest_loguniform("weight_decay", 1e-5, 1e-1)
    config["batch_size"] = trial.suggest_categorical("batch_size", [16, 32, 64])

    train_loader, val_loader = create_dataloaders(config["batch_size"])
    model, optimizer, device = initialize_model(config)

    train_acc, train_loss = train_epoch(model, train_loader, optimizer, device)
    # Here we only use loss as the objective
    val_acc, val_loss, _, _, _, _ = eval_model(model, val_loader, device)
    return val_loss

# Run hyperparameter tuning
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=10)

# # ---------------------- Final Fine-Tuning with Gradual Unfreezing ---------------------- #
# # Use best hyperparameters from tuning for final fine-tuning.
# best_params = study.best_params
# config = get_config()
# config.update(best_params)
# config["freeze_layers"] = False     # Unfreeze for fine-tuning
# config["gradual_unfreeze"] = True

# train_loader, val_loader = create_dataloaders(config["batch_size"])
# model, optimizer, device = initialize_model(config)

# # Fine-tuning loop with gradual unfreezing and evaluation of extra metrics.
# for epoch in range(config["num_epochs"]):
#     if config.get("gradual_unfreeze", False):
#         # Determine number of layers to unfreeze this epoch.
#         layers_unfrozen = gradual_unfreeze(model, epoch, config["num_epochs"])
#         # Add any newly unfrozen parameters to the optimizer.
#         new_params = []
#         for layer in model.bert.encoder.layer[-layers_unfrozen:]:
#             for param in layer.parameters():
#                 # Check if parameter requires grad and is not already in the optimizer.
#                 if param.requires_grad and not any(param in group['params'] for group in optimizer.param_groups):
#                     new_params.append(param)
#         if new_params:
#             optimizer.add_param_group({
#                 'params': new_params,
#                 'lr': config["learning_rate_bert"],
#                 'weight_decay': config["weight_decay"]
#             })
#         print(f"Epoch {epoch+1}/{config['num_epochs']}: Unfrozen {layers_unfrozen} BERT layers")

#     print(f"Epoch {epoch+1}/{config['num_epochs']}")
#     train_acc, train_loss = train_epoch(model, train_loader, optimizer, device)
#     # Evaluate and compute accuracy, loss, precision, recall, f1, and AUC
#     val_acc, val_loss, precision, recall, f1, auc = eval_model(model, val_loader, device)
#     print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
#     print(f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")
#     print(f"Precision: {precision:.4f} | Recall: {recall:.4f} | F1-score: {f1:.4f} | AUC: {auc if auc is not None else 'N/A'}")


# ---------------------- Final Fine-Tuning with Gradual Unfreezing ---------------------- #
# Use best hyperparameters from tuning for final fine-tuning.
best_params = study.best_params
config = get_config()
config.update(best_params)
config["freeze_layers"] = False     # Unfreeze for fine-tuning
config["gradual_unfreeze"] = True

train_loader, val_loader = create_dataloaders(config["batch_size"])
model, optimizer, device = initialize_model(config)

# Fine-tuning loop with gradual unfreezing and evaluation of extra metrics.
for epoch in range(config["num_epochs"]):
    if config.get("gradual_unfreeze", False):
        # Determine number of layers to unfreeze this epoch.
        layers_unfrozen = gradual_unfreeze(model, epoch, config["num_epochs"])

        # Add any newly unfrozen parameters to the optimizer.
        new_params = []
        for layer in model.bert.encoder.layer[-layers_unfrozen:]:
            for param in layer.parameters():
                if param.requires_grad:
                    # Check if the parameter is not already in the optimizer
                    if not any(torch.equal(param, p) for group in optimizer.param_groups for p in group['params']):
                        new_params.append(param)

        if new_params:
            optimizer.add_param_group({
                'params': new_params,
                'lr': config["learning_rate_bert"],
                'weight_decay': config["weight_decay"]
            })

        print(f"Epoch {epoch+1}/{config['num_epochs']}: Unfrozen {layers_unfrozen} BERT layers")

    print(f"Epoch {epoch+1}/{config['num_epochs']}")
    train_acc, train_loss = train_epoch(model, train_loader, optimizer, device)
    # Evaluate and compute accuracy, loss, precision, recall, f1, and AUC
    val_acc, val_loss, precision, recall, f1, auc = eval_model(model, val_loader, device)
    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f}")
    print(f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")
    print(f"Precision: {precision:.4f} | Recall: {recall:.4f} | F1-score: {f1:.4f} | AUC: {auc if auc is not None else 'N/A'}")

[I 2025-04-08 13:13:21,121] A new study created in memory with name: no-name-49e10249-d0c5-47a8-adef-e9ffb6f68565
<ipython-input-27-90b903da4988>:208: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["learning_rate_bert"] = trial.suggest_loguniform("learning_rate_bert", 1e-6, 5e-5)
<ipython-input-27-90b903da4988>:209: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["learning_rate_classifier"] = trial.suggest_loguniform("learning_rate_classifier", 1e-5, 1e-2)
<ipython-input-27-90b903da4988>:210: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["weight_decay"] = trial.suggest_loguniform("weight_decay", 1e-5, 1e-1)
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at yiyanghkust/finbert-pretrain and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Training: 100%|██████████| 79/79 [43:45<00:00, 33.23s/it]
Evaluating: 100%|██████████| 20/20 [09:21<00:00, 28.07s/it]
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2025-04-08 14:06:28,741] Trial 0 finished with value: 0.7401874274015426 and parameters: {'learning_rate_bert': 1.030517494255714e-06, 'learning_rate_classifier': 0.00025291583059914517, 'weight_decay': 0.01985106752091697, 'batch_size': 64}. Best is trial 0 with value: 0.7401874274015426.
<ipython-input-27-90b903da4988>:208: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["learning_rate_bert"] = trial.suggest_loguniform("learning_rate_bert", 1e-6, 5e-5)
<ipython-input-27-90b903da4988>:209: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["learning_rate_classifier"] = trial.suggest_loguniform("learning_rate_classifier", 1e-5, 1e-2)
<ipython-input-27-90b903da4988>:210: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["weight_decay"] = trial.suggest_loguniform("weight_decay", 1e-5, 1e-1)
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at yiyanghkust/finbert-pretrain and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Training: 100%|██████████| 157/157 [40:52<00:00, 15.62s/it]
Evaluating: 100%|██████████| 40/40 [09:16<00:00, 13.91s/it]
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2025-04-08 14:56:38,787] Trial 1 finished with value: 0.6138598263263703 and parameters: {'learning_rate_bert': 3.5840146106772584e-05, 'learning_rate_classifier': 0.0004804569633773783, 'weight_decay': 0.00023502197456260368, 'batch_size': 32}. Best is trial 1 with value: 0.6138598263263703.
<ipython-input-27-90b903da4988>:208: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["learning_rate_bert"] = trial.suggest_loguniform("learning_rate_bert", 1e-6, 5e-5)
<ipython-input-27-90b903da4988>:209: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["learning_rate_classifier"] = trial.suggest_loguniform("learning_rate_classifier", 1e-5, 1e-2)
<ipython-input-27-90b903da4988>:210: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  config["weight_decay"] = trial.suggest_loguniform("weight_decay", 1e-5, 1e-1)
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at yiyanghkust/finbert-pretrain and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Training:  54%|█████▍    | 171/314 [20:56<17:30,  7.35s/it]
[W 2025-04-08 15:17:35,901] Trial 2 failed with parameters: {'learning_rate_bert': 1.6297340914810822e-06, 'learning_rate_classifier': 0.0001736155483461618, 'weight_decay': 0.00010988625696841975, 'batch_size': 16} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "<ipython-input-27-90b903da4988>", line 216, in objective
    train_acc, train_loss = train_epoch(model, train_loader, optimizer, device)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-27-90b903da4988>", line 77, in train_epoch
    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/bert/modeling_bert.py", line 1673, in forward
    outputs = self.bert(
              ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/bert/modeling_bert.py", line 1142, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/pytorch_utils.py", line 254, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/bert/modeling_bert.py", line 640, in feed_forward_chunk
    layer_output = self.output(intermediate_output, attention_output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/models/bert/modeling_bert.py", line 552, in forward
    hidden_states = self.dense(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2025-04-08 15:17:35,907] Trial 2 failed with value None.

KeyboardInterrupt:

## Discussion

The training results indicate that the model's performance improved over the three epochs, with validation accuracy increasing from 81.61% to 84.24%. However, the validation loss increased from 0.4501 to 0.4925, suggesting potential overfitting.

**Key Findings:**

Validation Accuracy vs. Loss: The rise in validation accuracy alongside the increase in validation loss may indicate overfitting, where the model performs well on training data but less effectively on unseen data.

Precision, Recall, F1-Score, and AUC remained relatively stable across epochs, with slight improvements observed. The AUC values suggest that the model effectively distinguishes between classes.

**Analysis**

Overfitting Indicators: The validation loss increase, despite higher accuracy, points to overfitting. This occurs when the model learns noise in the training data, impairing its generalization to new data.

Stable Performance Metrics: The consistent precision, recall, F1-score, and AUC values imply that the model's ability to balance false positives and false negatives, as well as its overall classification performance, remained steady.

**Suggestions for Improvement:**

Regularization Techniques: Implement methods like dropout or L2 regularization to prevent overfitting.

Early Stopping: Monitor validation loss and halt training when it starts to increase, indicating potential overfitting.

Cross-Validation: Use k-fold cross-validation to assess model performance across different data subsets


**Strengths & Weaknesses**

Strengths:

Improved Performance: Fine-tuning pre-trained models like BERT allows for leveraging existing knowledge, leading to enhanced performance on specific tasks without training from scratch.

Efficient Training: Utilizing pre-trained models reduces the amount of data and computational resources required for training, making the process more efficient.

Effective Transfer Learning: Gradual unfreezing helps in adapting models to new tasks by progressively unfreezing layers, which can prevent catastrophic forgetting and improve generalization.

Weaknesses:

Overfitting Risks: Fine-tuning on small datasets can lead to overfitting, where the model performs well on training data but poorly on unseen data.

Complexity in Layer Management: Implementing gradual unfreezing requires careful management of layer training schedules, which can add complexity to the training process.

Resource Intensive: Despite being more efficient than training from scratch, fine-tuning large models like BERT still demands significant computational resources, which may be a limitation for some practitioners.

**Model Architecture choice:**

I decide to fine-tune a pre-trained finbert model by simply loading the model from huggingface. Therefore, the model architecture follows that if in-built finbert, where FinBERT consists of 12 Transformer encoder layers, uses ReLU (Rectified Linear Unit) as the activation function. FinBERT also employs dropout regularization and Layer Normalization.

**Hyperparameter Tuning:**

I decide to use Bayesian Optimization with optuna to find the best hyperparameters, as Bayesian Optimisation is mostly known to be better tha traditional gridsearch [(link)](https://medium.com/distributed-computing-with-ray/hyperparameter-optimization-for-transformers-a-guide-c4e32c6c989b).
Also, my initial hyperparameter initialization is based on literature which have shown they are mostly decent to use.

Based on [(link)](https://datascience.stackexchange.com/questions/64583/what-are-the-good-parameter-ranges-for-bert-hyperparameters-while-finetuning-it?utm_source=chatgpt.com):

Learning Rate: A learning rate of 2e-5 is commonly used for fine-tuning BERT models. This choice is supported by findings that a lower learning rate helps prevent catastrophic forgetting during fine-tuning.

Batch Size: A batch size of 32 is standard for BERT fine-tuning tasks. This size balances computational efficiency with model performance.

Number of Epochs: Fine-tuning BERT for 3 epochs is typical, as it often leads to optimal performance without overfitting.

Weight Decay: A weight decay of 0.01 is commonly used to prevent overfitting by penalizing large weights.

I have also decided to not tune the number of epochs as it becomes too compuationally expensive, and based on [link](https://medium.com/distributed-computing-with-ray/hyperparameter-optimization-for-transformers-a-guide-c4e32c6c989b), epochs is actually one of the least important hyperparameters.



**Fine-tuning**
When executing Baysian Optimisation for hyperparameters, the BERT layers were freezed for efficient execution.
When fine-tuning Finbert, I implemented gradual unfreezing as a technique.

**Challenges/Obstacles**:

The most challenging part of this project besides implementing tuning techniques would be data sourcing, labelling and preprocessing.
As I chose a relatively more rare and novel problem statement to classify 'confident', 'uncertain' & 'neutral', it has subtle differences from sentiment analysis.




**Solutions Employed**

I intially use FLAN-T5 to autotmatically label my data, but found out that it was very inaccurate in clasdifying text data. Hence, I switched to using RoberTA that is fined-tuned on twitter sentiments to label my data. After manually reviewing the labels, many confident and uncertain statements are correctly labelled as positive and negative respectively.

However, this also has drawbacks. A poitive sentiment doesn't always imply confidence. For instance, "Our situation will continue to improve, assuming market conditions are stable." will likely be a positive sentiment, however, it is more 'uncertain' than 'confident'.

Hence, using sentiment-trained RoberTa to automatically label my data and map 'Positive' to 'Confident' is not ideal.



**Future Direction/Improvement**

Ideally, ignoring time constraints and manpower, all sentences should be manually labelled to more accurately capture the nuances of confidence and uncertainty. Addtionally, a potential improvement to try out, is to create synthetic data tailored to the confidence labels.

# Test

In [1]:
import torch
from torch import nn
from transformers import BertTokenizer, BertModel
from torch.optim import AdamW
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from tqdm import tqdm

In [2]:
torch.manual_seed(42)

# Set device (GPU if available, else CPU)
device = (
    "mps"
    if torch.backends.mps.is_available()
    else "cuda"
    if torch.cuda.is_available()
    else "cpu"
)
device = torch.device(device)
print(f"Using device: {device}")

Using device: cpu

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
# demo data from https://www.kaggle.com/datasets/ankurzing/sentiment-analysis-for-financial-news?resource=download
data = pd.read_csv('/content/drive/MyDrive/DSA4265/Assignment 1/all-data.csv', names=['label', 'text'], encoding='utf-8', encoding_errors='ignore')

In [8]:
# Create a mapping dictionary
label_map = {
    'neutral': 0,
    'positive': 1,
    'negative': 2
}

# Apply the mapping to the 'label' column
data['label'] = data['label'].map(label_map)

In [9]:
# Split data ensuring indices are reset
train_texts, val_texts, train_labels, val_labels = train_test_split(
    data['text'].reset_index(drop=True),
    data['label'].reset_index(drop=True),
    test_size=0.2,
    random_state=42
)

In [10]:
# Initialize tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [15]:
# class NewsDataset(Dataset):
#     def __init__(self, texts, labels, tokenizer, max_length=128):
#         # Convert to list to ensure sequential indexing
#         self.texts = texts.tolist() if hasattr(texts, 'tolist') else list(texts)
#         self.labels = labels.tolist() if hasattr(labels, 'tolist') else list(labels)
#         self.tokenizer = tokenizer
#         self.max_length = max_length

#     def __len__(self):
#         return len(self.texts)

#     def __getitem__(self, idx):
#         print(idx)
#         text = str(self.texts[idx])
#         label = self.labels[idx]

#         encoding = self.tokenizer.encode_plus(
#             text,
#             add_special_tokens=True,
#             max_length=self.max_length,
#             return_token_type_ids=False,
#             padding='max_length',
#             truncation=True,
#             return_attention_mask=True,
#             return_tensors='pt'
#         )
#         return {
#             'input_ids': encoding['input_ids'].flatten(),
#             'attention_mask': encoding['attention_mask'].flatten(),
#             'labels': torch.tensor(label, dtype=torch.long)
#         }



# ---------------------- Custom Dataset ---------------------- #
class EarningsCallDataset(Dataset):
    """
    Custom dataset that tokenizes input texts and returns a dictionary
    with input_ids, attention_mask, and labels.
    """
    def __init__(self, texts, labels, tokenizer, max_length=128):
        # Convert to list if not already
        self.texts = texts.tolist() if hasattr(texts, 'tolist') else list(texts)
        self.labels = labels.tolist() if hasattr(labels, 'tolist') else list(labels)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        # Get the text and label at index idx and tokenize
        print(idx)
        text = str(self.texts[idx])
        label = self.labels[idx]
        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,       # Add special tokens ([CLS], [SEP])
            max_length=self.max_length,
            return_token_type_ids=False,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'            # Return PyTorch tensors
        )
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

In [16]:
# Create datasets
train_dataset = EarningsCallDataset(train_texts, train_labels, tokenizer)
val_dataset = EarningsCallDataset(val_texts, val_labels, tokenizer)

# Create data loaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

In [17]:
for batch in tqdm(train_loader, desc="Training"):
    # # Move batch to device (CPU/GPU)
    # input_ids = batch['input_ids'].to(device)
    # attention_mask = batch['attention_mask'].to(device)
    # labels = batch['labels'].to(device)

    print(batch)

Training:   2%|▏         | 2/122 [00:00<00:10, 11.04it/s]

3202
3070
1751
1946
2447
1042
1381
2546
2165
367
992
50
997
984
273
2806
115
1331
1293
3209
2334
1238
1398
1697
2031
837
2542
784
2802
1136
1349
2956
{'input_ids': tensor([[ 101, 2036, 1996,  ...,    0,    0,    0],
        [ 101, 2006, 1996,  ...,    0,    0,    0],
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 3393, 7382,  ...,    0,    0,    0],
        [ 101, 2053, 3361,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0])}
2781
2407
1845
2350
1848
3598
1179
2505
486
439
584
4
1935
2336
2013
2384
3378
3097
2967
320
3411
3139
3220
2058
2945
2004
1276
2176
1041
1890
1199
2036
{'input_ids': tensor([[ 101, 2756, 2244,  ...,    0,    0,    0],
        [ 101, 1037, 2561,  ...,    0,    0,    0],
        [ 101, 2023, 2895,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 2005, 1996,  ...,    0,    0,    0],
        [ 101, 1042, 1011,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 0, 2, 1, 1, 2])}
3145
2241
2603
3189
1560
2283
3471
3623

Training:   3%|▎         | 4/122 [00:00<00:11, 10.32it/s]

3527
378
2423
1478
1880
3665
1510
605
3203
364
372
1084
980
3101
410
1780
3601
1789
1896
3114
460
1821
1409
2783
{'input_ids': tensor([[ 101, 2429, 2000,  ...,    0,    0,    0],
        [ 101, 2859, 4895,  ...,    0,    0,    0],
        [ 101, 5719, 3136,  ...,    0,    0,    0],
        ...,
        [ 101, 1048, 1004,  ...,    0,    0,    0],
        [ 101, 1036, 1036,  ...,    0,    0,    0],
        [ 101, 3977, 2097,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 2, 0, 2,
        0, 0, 2, 0, 0, 0, 1, 2])}
2758
307
1215
1253
2233
1593
154
1981
3873
771
867
3393
3412
1950
2599
2724
3167
3490
407
2854
3575
3030
2767
174
2986
3433
1714
3029
1154
1687
163
1550
{'input_ids': tensor([[ 101, 4082, 5618,  ...,    0,    0,    0],
        [ 101, 1996, 3820,  ...,    0,    0,    0],
        [ 101, 5658, 4341,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 2561,  ...,    0,    0,    0],
        [ 101, 2101, 2006,  ...,    0,    0,    0],
        [ 101, 2656, 2254,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 2, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 0, 0, 0, 1])}
2358
1229
57
2160
1930
3077
3414
168
216
693

Training:   5%|▍         | 6/122 [00:00<00:10, 10.73it/s]

380
1132
265
530
3224
2568
368
2722
3343
532
3472
1877
2212
3076
232
3605
2128
3353
254
2561
1631
1599
{'input_ids': tensor([[  101,  1049,  1011,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101, 25430,  2098,  ...,     0,     0,     0],
        ...,
        [  101, 20481, 10581,  ...,     0,     0,     0],
        [  101, 16565,  2566,  ...,     0,     0,     0],
        [  101,  1996,  2457,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 2, 0, 0, 1, 1])}
2537
1053
2687
2732
1129
1243
1610
3517
1310
999
2324
3305
2326
3197
165
1222
3667
700
1923
1086
1830
3534
3003
1197
1884
2103
1735
2815
2108
239
2079
2017
{'input_ids': tensor([[  101,  2077, 14352,  ...,     0,     0,     0],
        [  101,  2043,  2949,  ...,     0,     0,     0],
        [  101,  3653,  2696,  ...,     0,     0,     0],
        ...,
        [  101, 10093,  4355,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  1996,  6983,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 2, 2, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0,
        0, 1, 0, 0, 1, 0, 0, 0])}
903
2145
3376
2370
1138
855
366
1655
14
1300
1194
2982
2620
2389
1684
3801
326
3817
697
167

Training:   7%|▋         | 8/122 [00:00<00:10, 10.46it/s]

2253
3301
3732
972
2006
838
2867
379
58
661
124
219
{'input_ids': tensor([[  101,  6983, 21368,  ...,     0,     0,     0],
        [  101,  5494,  1997,  ...,     0,     0,     0],
        [  101,  2119, 10940,  ...,     0,     0,     0],
        ...,
        [  101,  2429,  2000,  ...,     0,     0,     0],
        [  101,  5622,  6525,  ...,     0,     0,     0],
        [  101,  1996,  3941,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 2, 0,
        0, 0, 0, 2, 2, 2, 0, 1])}
1806
2975
3768
766
1493
613
874
347
2062
1117
1894
2030
2556
583
987
1820
429
3749
3839
1221
2248
944
2250
876
2403
1576
2719
1124
2338
2263
3579
3730
{'input_ids': tensor([[ 101, 1996, 7654,  ...,    0,    0,    0],
        [ 101, 1996, 2391,  ...,    0,    0,    0],
        [ 101, 5564, 1010,  ...,    0,    0,    0],
        ...,
        [ 101, 1999, 6435,  ...,    0,    0,    0],
        [ 101, 6983, 8139,  ...,    0,    0,    0],
        [ 101, 1996, 3820,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2,
        0, 0, 0, 1, 0, 2, 2, 0])}
2264
513
1959
2140
77
1389
2906
1817
2347
3304
1244
3179
723
3256
2195
392
2016
1973
1190
1460
2978
3354
455
138
3709

Training:   8%|▊         | 10/122 [00:00<00:10, 10.53it/s]

2897
434
926
17
3066
1584
2147
{'input_ids': tensor([[  101,  4518,  5804,  ...,     0,     0,     0],
        [  101,  8589,  2085,  ...,     0,     0,     0],
        [  101,  1006,  4748,  ...,     0,     0,     0],
        ...,
        [  101,  3569, 22098,  ...,  1010,  5786,   102],
        [  101,  2119,  4082,  ...,     0,     0,     0],
        [  101,  1996,  2573,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 2, 0, 0, 1, 0, 1, 0])}
1511
1211
2305
441
1732
2576
3259
3261
779
3151
3273
575
3566
112
3069
1039
227
3276
2255
2271
2136
2340
1401
1707
2770
2060
684
973
2040
757
694
788
{'input_ids': tensor([[  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  1996,  2231,  ...,     0,     0,     0],
        [  101,  1996,  2047,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  3930,  ...,     0,     0,     0],
        [  101, 13926,  5243,  ...,     0,     0,     0],
        [  101,  1996, 20600,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 2,
        1, 0, 1, 0, 0, 1, 1, 1])}
3089
1135
447
3751
3327
6
1483
2951
3267
277
2949
589
2935
3363
1415
2491
256
3544
2418
3290
3252
13
3784
470
2950
1994
2228
1309
1345
2705
3361

Training:  10%|▉         | 12/122 [00:01<00:10, 10.71it/s]

3402
{'input_ids': tensor([[ 101, 1996, 7286,  ...,    0,    0,    0],
        [ 101, 1041, 2497,  ...,    0,    0,    0],
        [ 101, 5618, 2077,  ...,    0,    0,    0],
        ...,
        [ 101, 5658, 3037,  ...,    0,    0,    0],
        [ 101, 4518, 5804,  ...,    0,    0,    0],
        [ 101, 1996, 2193,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 2, 0,
        1, 0, 0, 0, 0, 1, 0, 2])}
381
655
3578
2702
501
3660
2028
271
817
419
824
2670
1936
1588
2738
402
639
825
893
200
3831
1314
1049
2285
1813
2477
1142
854
130
906
1556
2761
{'input_ids': tensor([[ 101, 4082, 5618,  ...,    0,    0,    0],
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 1996, 6614,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 6983,  ...,    0,    0,    0],
        [ 101, 1996, 2924,  ...,    0,    0,    0],
        [ 101, 1037, 1004,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 1])}
1462
3279
2239
3195
3658
1411
3432
2930
2129
3683
1336
2884
3856
1290
1212
2051
83
471
1979
223
1391
1271
1766
304
125
280
1176
2148
3308
1699
2582
3736
{'input_ids': tensor([[  101,  6983, 16016,  ...,     0,     0,     0],
        [  101,  6605,  2472,  ...,     0,     0,     0],
        [  101, 22098, 22108,  ...,     0,     0,     0],
        ...,
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101, 12849,  4246,  ...,     0,     0,     0],
        [  101,  2429,  2000,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 2, 2, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 0, 1])}
3349
963
1982
46

Training:  11%|█▏        | 14/122 [00:01<00:10, 10.58it/s]

228
2909
2639
3036
3057
1823
395
406
776
2795
1454
464
2068
2554
3009
3388
1545
303
207
2823
3672
1825
3347
910
2490
108
640
1428
{'input_ids': tensor([[  101,  1996,  5396,  ...,     0,     0,     0],
        [  101, 16565,  2566,  ...,     0,     0,     0],
        [  101,  4082,  5618,  ...,     0,     0,     0],
        ...,
        [  101,  6983,  2833,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  2004,  2112,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 2, 0, 1, 1, 0, 0])}
1955
2043
3102
1590
570
1764
2507
2097
1489
2322
790
604
2021
1461
1934
2803
3233
1663
3755
1637
3723
2710
1784
2870
2528
3564
3129
574
2117
1878
2302
1101
{'input_ids': tensor([[  101, 15440, 11176,  ...,     0,     0,     0],
        [  101, 20248,  5054,  ...,     0,     0,     0],
        [  101,  2105,  5539,  ...,     0,     0,     0],
        ...,
        [  101,  1999,  1037,  ...,     0,     0,     0],
        [  101,  3795,  2166,  ...,     0,     0,     0],
        [  101,  4082,  5618,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 2, 0, 1])}
2591
2677
1734
1628
2474
107
3348
1868
3582
492
717
1742
32
3096
1986
1414

Training:  15%|█▍        | 18/122 [00:01<00:08, 11.64it/s]

234
3193
1486
2231
849
143
1911
1619
3319
3465
2948
1836
3621
333
1332
2550
{'input_ids': tensor([[  101, 12886,  2097,  ...,     0,     0,     0],
        [  101,  1996,  2880,  ...,     0,     0,     0],
        [  101,  6983,  4640,  ...,     0,     0,     0],
        ...,
        [  101, 17768, 21823,  ...,     0,     0,     0],
        [  101,  1996,  5761,  ...,     0,     0,     0],
        [  101, 12316,  2102,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 1, 1, 1, 0, 1])}
909
3060
3630
1835
1060
2192
1783
2805
901
2574
1165
1869
1497
1203
3560
2923
3714
1064
2990
428
585
3479
3450
2268
457
1377
2489
3082
1055
847
3092
2544
{'input_ids': tensor([[ 101, 1996, 2047,  ...,    0,    0,    0],
        [ 101, 6728, 1011,  ...,    0,    0,    0],
        [ 101, 4082, 2765,  ...,    0,    0,    0],
        ...,
        [ 101, 1036, 1036,  ...,    0,    0,    0],
        [ 101, 4082, 5618,  ...,    0,    0,    0],
        [ 101, 4654, 2884,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 2, 0, 1, 1, 1, 0, 0, 1, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0,
        0, 1, 1, 0, 0, 0, 2, 0])}
3239
88
2161
2411
591
2765
2211
3753
2560
1034
3818
237
2317
318
2138
2953
1554
1275
81
3855
2151
2549
1348
1147
1729
1693
1860
2916
742
178
3020
1842
{'input_ids': tensor([[ 101, 1045, 4067,  ...,    0,    0,    0],
        [ 101, 5618, 2044,  ...,    0,    0,    0],
        [ 101, 1036, 1036,  ...,    0,    0,    0],
        ...,
        [ 101, 2009, 2001,  ...,    0,    0,    0],
        [ 101, 2047, 6768,  ...,    0,    0,    0],
        [ 101, 2035, 1997,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1])}
3324
2450
1765
2653
1219
296
2729
1061

Training:  16%|█▋        | 20/122 [00:01<00:09, 11.06it/s]

638
2875
109
289
2754
732
1539
1801
2911
3005
744
1248
1770
2316
3812
1467
2992
2798
1164
2888
1075
1838
2510
3464
{'input_ids': tensor([[  101, 18347, 15687,  ...,     0,     0,     0],
        [  101,  2423,  2233,  ...,     0,     0,     0],
        [  101, 11899,  1010,  ...,     0,     0,     0],
        ...,
        [  101,  2426,  3259,  ...,     0,     0,     0],
        [  101,  5678,  1010,  ...,     0,     0,     0],
        [  101,  2708,  3237,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 0, 0, 0, 2, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 2])}
3530
2200
2492
1374
593
73
561
3545
3296
1204
3362
968
981
957
36
1566
2654
1146
5
1932
2279
3702
1551
2453
2711
2683
2757
1119
1782
3470
405
1387
{'input_ids': tensor([[  101,  2429,  2000,  ...,     0,     0,     0],
        [  101,  2429,  2000,  ...,     0,     0,     0],
        [  101,  1996, 15581,  ...,     0,     0,     0],
        ...,
        [  101,  2039,  2213,  ...,     0,     0,     0],
        [  101,  1996,  2561,  ...,     0,     0,     0],
        [  101,  1006,  4748,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 2, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
        2, 0, 1, 0, 0, 0, 0, 2])}
822
946
2829
2102
2230
911
3445
249
2583
2443
3373
3219

Training:  18%|█▊        | 22/122 [00:02<00:09, 10.49it/s]

2469
3495
569
3188
1900
494
3181
1239
1015
3606
1274
3086
3001
2538
1469
152
3044
3026
3199
1036
{'input_ids': tensor([[  101,  1999,  2337,  ...,     0,     0,     0],
        [  101, 10556, 19666,  ...,     0,     0,     0],
        [  101,  1996,  3393,  ...,     0,     0,     0],
        ...,
        [  101, 16012, 16584,  ...,     0,     0,     0],
        [  101,  2625,  2084,  ...,     0,     0,     0],
        [  101,  1999,  2384,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 0,
        0, 2, 0, 0, 0, 0, 0, 0])}
3739
2287
2669
1295
3722
685
1855
720
2866
60
2837
26
834
2963
3247
3370
953
1857
623
1522
1315
3083
3006
3442
865
1231
813
2055
797
964
1905
493
{'input_ids': tensor([[  101,  2349,  2000,  ...,     0,     0,     0],
        [  101,  1011,  5618,  ...,     0,     0,     0],
        [  101,  2119,  4082,  ...,     0,     0,     0],
        ...,
        [  101, 10556, 19666,  ...,     0,     0,     0],
        [  101, 27019,  3617,  ...,     0,     0,     0],
        [  101,  1996,  2197,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 0, 0, 2, 0, 0, 2, 0, 2, 1, 1, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1,
        1, 0, 0, 2, 1, 1, 0, 0])}
2764
322
1597
1659
3127
1990
1175
480
339
3815
2743
1113
933
1330
1021
869
2198
2286
1207
3337
1898
2029
3218
1068
3260
1257
1850
1621

Training:  20%|█▉        | 24/122 [00:02<00:08, 11.84it/s]

1679
27
2931
3565
{'input_ids': tensor([[ 101, 2012, 2556,  ...,    0,    0,    0],
        [ 101, 1996, 3466,  ...,    0,    0,    0],
        [ 101, 1996, 3206,  ...,    0,    0,    0],
        ...,
        [ 101, 2023, 3536,  ...,    0,    0,    0],
        [ 101, 1996, 2817,  ...,    0,    0,    0],
        [ 101, 1036, 1036,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 1])}
609
3822
2826
1618
1304
313
2359
1939
2498
1355
2329
2625
3854
1943
156
2100
1798
12
2588
3503
1822
2395
541
3041
3782
3171
2709
889
802
2791
2937
1040
{'input_ids': tensor([[  101,  1998,  2043,  ...,     0,     0,     0],
        [  101,  3737, 18649,  ...,     0,     0,     0],
        [  101,  6983,  2533,  ...,     0,     0,     0],
        ...,
        [  101, 11163, 18168,  ...,     0,     0,     0],
        [  101,  1996,  6994,  ...,     0,     0,     0],
        [  101, 12331,  1006,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 2, 1, 2, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 1])}
139
519
2741
1475
3389
2075
1647
2703
377
3192
2032
3214
1924
1088
2045
2928
1157
2024
1824
3317
1925
2727
1426
2689
2601
1500
1224
1870
3334
1532
3510
3297
{'input_ids': tensor([[ 101, 5034, 2615,  ...,    0,    0,    0],
        [ 101, 7157, 1059,  ...,    0,    0,    0],
        [ 101, 1036, 1036,  ...,    0,    0,    0],
        ...,
        [ 101, 2091, 2000,  ...,    0,    0,    0],
        [ 101, 4640, 4701,  ...,    0,    0,    0],
        [ 101, 1996, 2194,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 2, 2, 1, 0, 1, 2, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 2, 2, 1])}
3021
2841
2831
2044
3222
2842
348
2027
2130
1685
3794
617

Training:  21%|██▏       | 26/122 [00:02<00:08, 11.15it/s]

3
1370
2987
1334
3265
978
1688
2700
2678
2399
1094
3384
737
390
633
2643
1507
2063
2663
3827
{'input_ids': tensor([[  101,  2006,  9317,  ...,     0,     0,     0],
        [  101,  1036,  2624,  ...,     0,     0,     0],
        [  101, 10556, 19145,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  1996,  3206,  ...,     0,     0,     0],
        [  101,  2256,  3115,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 2, 1, 0, 1, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 2, 0, 1, 0, 2, 1, 0,
        0, 0, 1, 1, 0, 2, 0, 1])}
1961
2362
373
1837
3311
3772
1753
242
2564
2942
2892
334
3268
1009
2208
731
2394
1488
810
688
2686
2519
3500
3599
3502
1240
135
1834
1573
3435
3848
2840
{'input_ids': tensor([[ 101, 2429, 2000,  ...,    0,    0,    0],
        [ 101, 2195, 2312,  ...,    0,    0,    0],
        [ 101, 2002, 2056,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 3296,  ...,    0,    0,    0],
        [ 101, 1048, 1009,  ...,    0,    0,    0],
        [ 101, 1996, 6839,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 2, 2, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1,
        0, 2, 2, 1, 0, 0, 0, 0])}
2242
1073
830
399
734
1689
2014
2684
3050
1278
2740
1066

Training:  23%|██▎       | 28/122 [00:02<00:10,  8.78it/s]

396
808
241
1390
2613
3493
3865
2834
704
3048
2547
3049
2504
945
2708
1504
1026
2414
2819
1774
{'input_ids': tensor([[  101,  6285, 15544,  ...,     0,     0,     0],
        [  101,  1996,  5950,  ...,     0,     0,     0],
        [  101,  2429,  2000,  ...,     0,     0,     0],
        ...,
        [  101,  2235,  9387,  ...,     0,     0,     0],
        [  101,  1041, 16313,  ...,     0,     0,     0],
        [  101,  2651,  1010,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 2, 1, 2,
        0, 1, 0, 2, 1, 2, 1, 0])}
3085
3095
2551
2488
104
218
3000
780
1270
1089
1839
2522
206
1107
349
1642
1471
3004
3857
354
24
3137
1666
316
696
2087
1844
2996
3814
1634
1325
1602
{'input_ids': tensor([[  101,  2023,  2047,  ...,     0,     0,     0],
        [  101,  2537,  2012,  ...,     0,     0,     0],
        [  101,  1996,  1041,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  3800,  ...,     0,     0,     0],
        [  101,  1043,  8523,  ...,     0,     0,     0],
        [  101, 13433,  3619,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 0])}
2461
2895
2376
2291
1508
3283
3770
761
811
886
2762
484
2459
1186
55
1367
2852
1320
2210
426
2533
2431
3019
511
1682
1430
2572
162
2307
1037
1354

Training:  25%|██▌       | 31/122 [00:03<00:10,  8.52it/s]

1892
{'input_ids': tensor([[  101,  2004, 27605,  ...,     0,     0,     0],
        [  101,  1996,  2561,  ...,     0,     0,     0],
        [  101,  1996,  5096,  ...,     0,     0,     0],
        ...,
        [  101,  1996, 16360,  ...,     0,     0,     0],
        [  101,  2047,  4031,  ...,     0,     0,     0],
        [  101,  2104,  1996,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 2, 0, 0, 1, 0, 0, 2, 1, 2, 2, 0, 2, 0, 1, 0, 0, 1, 0, 2, 0, 0,
        2, 0, 2, 2, 0, 2, 1, 0])}
435
1252
3116
2471
169
913
1795
3282
2983
1476
2452
1791
1269
1432
2473
3263
755
1342
1624
72
3235
601
3113
3804
880
194
3475
1347
2375
3333
286
2847
{'input_ids': tensor([[  101,  6983, 27902,  ...,     0,     0,     0],
        [  101, 24797,  1011,  ...,     0,     0,     0],
        [  101,  1999,  2804,  ...,     0,     0,     0],
        ...,
        [  101, 19021,  8059,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 1])}
1464
3117
536
1337
99
1214
290
3505
1416
85
3187
2056

Training:  26%|██▌       | 32/122 [00:03<00:10,  8.44it/s]

1649
3341
1948
1166
1662
2656
2330
2952
1317
590
1786
2046
1975
2222
3651
2035
1885
229
1722
2984
{'input_ids': tensor([[  101,  5658,  4341,  ...,     0,     0,     0],
        [  101,  2449, 28908,  ...,     0,     0,     0],
        [  101,  1996,  4082,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  7654,  ...,     0,     0,     0],
        [  101,  7192,  1998,  ...,     0,     0,     0],
        [  101,  2019,  7327,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 2, 0, 1, 1, 0])}
2186
1144
3053
1596
1888
1218
607
2943
2333
2265
3212
2595
2993
1307
2363
3745
1074
752
1988
2007
2188
2589
3213
2154
1538
1847
1525
1910
2611
2746
253
3156
{'input_ids': tensor([[  101,  5658,  4341,  ...,     0,     0,     0],
        [  101,  6983,  4319,  ...,     0,     0,     0],
        [  101, 25430,  2098,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  3316,  ...,     0,     0,     0],
        [  101,  1996,  3206,  ...,     0,     0,     0],
        [  101,  2512, 12155,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 0, 2, 0, 1, 1, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0])}

Training:  28%|██▊       | 34/122 [00:03<00:11,  7.56it/s]

2680
1303
3310
3742
3200
934
1465
759
979
1589
3603
750
391
555
3786
2451
1630
1450
2454
2642
1851
3103
612
2005
2479
3250
35
2586
3604
3808
100
2135
{'input_ids': tensor([[  101, 12886,  2240,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  9089,  2063,  ...,     0,     0,     0],
        [  101,  2014,  2556,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 2, 1, 2, 0, 0, 0, 0, 1, 0, 2, 1, 2, 0, 1, 2, 0, 1, 1, 2, 0, 1, 2, 1,
        0, 0, 0, 0, 1, 0, 0, 0])}
370
1604
1365
2499
3207
937
1738
2057
1668
3345
1763
2156
2215
1004
179
1137
433
1872
3511
3541
1156
161
3539
299
293
1364
3454
3072
3693
1605
1727
3635
{'input_ids': tensor([[  101,  2023,  8775,  ...,     0,     0,     0],
        [  101, 19021,  8059,  ...,     0,     0,     0],
        [  101,  1999,  2285,  ...,     0,     0,     0],
        ...,
        [  101,  2006,  2327,  ...,     0,     0,     0],
        [  101,  1999,  2244,  ...,     0,     0,     0],
        [  101,  6983,  2968,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 2, 0, 1, 1, 0, 1, 2, 0, 2, 0,
        1, 1, 0, 0, 1, 2, 2, 2])}
1056
2071
1635
1402
3173
1933
2621
2073
1512
2485
3300
521
2790
3611
1579
2698
1587
68
1549
1140
2753
2612
2999
3531
1970
490
181
2374
629
709
1598
916

Training:  30%|███       | 37/122 [00:03<00:11,  7.57it/s]

{'input_ids': tensor([[  101,  2811,  2713,  ...,     0,     0,     0],
        [  101,  2089,  2756,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        ...,
        [  101,  1996, 12490,  ...,     0,     0,     0],
        [  101, 18414, 23573,  ...,     0,     0,     0],
        [  101,  2631,  1999,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 0, 0, 2, 2, 1, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 0, 0])}
3769
1000
1424
974
1346
1995
939
2681
2085
1938
1335
1541
2838
2421
3556
1382
3128
482
3098
352
2133
1758
3158
2349
1438
3271
3422
3221
1561
919
595
240
{'input_ids': tensor([[  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  1996,  2449,  ...,     0,     0,     0],
        [  101,  1999,  2804,  ...,     0,     0,     0],
        ...,
        [  101,  2007,  1996,  ...,     0,     0,     0],
        [  101,  1996,  2565,  ...,     0,     0,     0],
        [  101, 16565,  2566,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 2, 0, 0, 2, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 1, 1, 1,
        2, 0, 1, 1, 1, 1, 0, 0])}
1716
131
1617
572
2794
2441
2114
1452
3436
64
2463
1546
137
3649
412
2308
3728
2635
319
1159
3033
2304
2969
1085
3248
2327
819
1180
1439
1879
298
549
{'input_ids': tensor([[  101,  6983, 14316,  ...,     0,     0,     0],
        [  101,  1996,  2967,  ...,     0,     0,     0],
        [  101,  1996,  4322,  ...,     0,     0,     0],
        ...,
        [  101,  2076,  1996,  ...,     0,     0,     0],
        [  101,  1996,  2177,  ...,     0,     0,     0],
        [  101,  2122,  9259,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 0, 0, 2, 2, 0, 1, 0,
        0, 0, 0, 1, 1, 0, 2, 0])}
2401
2318
1076
1145
582
2267
2084
2234
1632
905
89
3466
1379
2105
3602
3312
422
3011
3115
3153
2976
2938
3802

Training:  34%|███▎      | 41/122 [00:04<00:07, 10.66it/s]

3494
2378
2065
3558
3274
2634
310
535
1913
{'input_ids': tensor([[  101,  5734,  3001,  ...,     0,     0,     0],
        [  101,  4283,  2000,  ...,     0,     0,     0],
        [  101,  1996, 28361,  ...,     0,     0,     0],
        ...,
        [  101,  4082,  5618,  ...,     0,     0,     0],
        [  101,  2538,  2255,  ...,     0,     0,     0],
        [  101,  1037,  2561,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 2, 1, 0, 0, 2, 1, 1, 0, 2, 0,
        0, 0, 0, 1, 0, 0, 1, 0])}
2446
1658
84
96
3172
3836
509
1723
2367
3136
1479
1614
1265
2877
3446
3563
3438
928
2812
1092
2940
1246
1063
1120
2848
3150
2668
39
2801
491
1283
545
{'input_ids': tensor([[  101,  6983,  3224,  ...,     0,     0,     0],
        [  101, 21368,  5737,  ...,     0,     0,     0],
        [  101,  2537,  4128,  ...,     0,     0,     0],
        ...,
        [  101,  2005,  1996,  ...,     0,     0,     0],
        [  101,  4082,  5618,  ...,     0,     0,     0],
        [  101,  2108,  3144,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 2, 0, 0, 1, 0])}
3394
1530
2775
3429
3232
1559
63
2369
3844
2853
3439
2020
147
991
851
1126
2111
2932
2701
3451
1964
1383
2676
831
2458
2355
3767
3025
16
2785
1453
1974
{'input_ids': tensor([[  101,  2429,  2000,  ...,     0,     0,     0],
        [  101,  1996,  2087,  ...,     0,     0,     0],
        [  101,  8915, 14511,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2193,  ...,     0,     0,     0],
        [  101,  1996,  2561,  ...,     0,     0,     0],
        [  101,  2747,  6152,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1,
        0, 0, 0, 1, 0, 0, 0, 0])}
133
1696
2385
1291
806

Training:  35%|███▌      | 43/122 [00:04<00:07, 10.95it/s]

3315
577
2581
1067
1849
3147
497
1951
2529
355
654
3409
1568
136
1567
1406
3331
2486
2513
2966
3652
736
34
3581
716
1228
1457
{'input_ids': tensor([[  101,  4013,  9080,  ...,     0,     0,     0],
        [  101,  6178,  2386,  ...,     0,     0,     0],
        [  101, 12849, 25032,  ...,     0,     0,     0],
        ...,
        [  101, 14405, 26065,  ...,     0,     0,     0],
        [  101,  1996,  6983,  ...,     0,     0,     0],
        [  101,  2023,  2097,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 2, 2, 1, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2,
        0, 0, 0, 0, 0, 0, 0, 1])}
3738
263
542
3473
1437
3288
159
1547
479
2437
188
2167
2682
2776
3372
3647
247
1106
2183
3569
809
2902
2320
1363
1306
2830
2626
902
1361
1386
1005
3125
{'input_ids': tensor([[  101,  7929, 11368,  ...,     0,     0,     0],
        [  101, 12456, 16339,  ...,     0,     0,     0],
        [  101,  2043,  2047,  ...,     0,     0,     0],
        ...,
        [  101,  2062,  2084,  ...,     0,     0,     0],
        [  101,  1996,  2922,  ...,     0,     0,     0],
        [  101,  6983,  2474,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 1])}
502
526
1445
1828
1841
3100
2180
799
3238
1007
2388
3760
98
3090
2587
1492
2503

Training:  37%|███▋      | 45/122 [00:04<00:06, 11.95it/s]

2918
2596
3546
106
3052
149
2170
3792
2494
18
512
1127
840
3824
1756
{'input_ids': tensor([[  101, 10495,  4082,  ...,     0,     0,     0],
        [  101,  2241,  2006,  ...,     0,     0,     0],
        [  101,  1996,  1041,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  3679,  ...,     0,     0,     0],
        [  101,  4283,  2000,  ...,     0,     0,     0],
        [  101,  1996,  3417,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 0, 1, 2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 0, 1, 0, 2,
        1, 0, 1, 1, 1, 0, 0, 0])}
1652
2260
940
86
3816
1854
2540
990
1700
3278
767
269
2197
2221
2460
2
1882
3258
1608
3234
1703
528
634
507
881
871
1744
1321
3518
576
1322
1277
{'input_ids': tensor([[  101,  4748,  2361,  ...,     0,     0,     0],
        [  101,  2656,  2255,  ...,     0,     0,     0],
        [  101,  3449, 19800,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2212,  ...,     0,     0,     0],
        [  101,  6983, 19309,  ...,     0,     0,     0],
        [  101,  1996,  1041,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 2, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 1, 0, 1, 1, 1, 0, 0])}
1557
1131
288
527
1490
3679
1093
2402
2606
1059
1562
1570
261
621
3719
3661
1226
317
160
3737
1006
2862
753
2391
3862
3875
3174
2091
360
1918
10
1540
{'input_ids': tensor([[ 101, 2012, 1996,  ...,    0,    0,    0],
        [ 101, 2007, 2023,  ...,    0,    0,    0],
        [ 101, 2035, 2024,  ...,    0,    0,    0],
        ...,
        [ 101, 2709, 2006,  ...,    0,    0,    0],
        [ 101, 1017, 2254,  ...,    0,    0,    0],
        [ 101, 7597, 1998,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 0, 2, 0, 2, 1, 2])}
2804
1187
2438
3520
3593
2294
3860
2650
3687
2555
463
1909
2651
487
3231
691
1071
3555
1876
417
3823
787
2778
2166
1081
3054
2123
3154
3111
122
2707
338
{'input_ids': tensor([[  101,  1996,  4117,  ...,     0,     0,     0],
        [  101,  1996,  3745,  ...,     0,     0,     0],
        [  101,  2009,  2003,  ...,     0,     0,     0],
        ...,
        [  101,  1996, 11443,  ...,     0,     0,     0],
        [  101,  1996,  2177,  ...,     0,     0,     0],
        [  101,  2009,  2003,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 2,
        0, 1, 0, 1, 0, 0, 1, 0])}

Training:  40%|████      | 49/122 [00:04<00:06, 11.98it/s]

786
3073
3762
357
2449
1266
2567
3662
1971
3453
2817
1650
1769
1105
2196
1241
1163
994
3326
3286
2466
1615
3303
2390
2545
2989
3554
2557
921
2257
565
1748
{'input_ids': tensor([[  101,  1999,  1996,  ...,     0,     0,     0],
        [  101,  1996,  2197,  ...,     0,     0,     0],
        [  101,  1996,  3237,  ...,     0,     0,     0],
        ...,
        [  101,  2004,  1037,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101, 16012,  9515,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 2, 1, 1, 0])}
3634
2624
1189
3681
890
651
1793
2858
2169
244
1886
3164
3615
3846
896
3299
1755
415
3748
3703
363
2342
2272
1586
1318
1045
151
3637
1122
1148
683
1223
{'input_ids': tensor([[  101,  4082,  5618,  ...,     0,     0,     0],
        [  101,  1999,  2804,  ...,     0,     0,     0],
        [  101,  5658,  5211,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  8361,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101,  2023, 12598,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 0, 0, 0, 1, 0, 1, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 0, 2, 0, 2, 1])}
882
1931
2444
3842
1046
552
3561
2913

Training:  42%|████▏     | 51/122 [00:05<00:06, 11.43it/s]

676
3122
1020
3017
1397
1024
1161
2356
3497
2223
1520
1057
315
2649
2886
1405
1901
804
1708
453
472
309
3109
2516
{'input_ids': tensor([[  101, 27523,  2361,  ...,     0,     0,     0],
        [  101,  2031, 19488,  ...,     0,     0,     0],
        [  101,  1996,  3643,  ...,     0,     0,     0],
        ...,
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101,  1037, 14056,  ...,     0,     0,     0],
        [  101,  3222,  3318,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 1, 1, 0, 1, 0, 1])}
1289
1583
82
1420
3182
632
2585
3509
846
568
2475
1442
2098
2559
386
3306
2632
2759
2592
92
1603
566
600
966
1737
3302
3176
3099
2641
192
1434
1985
{'input_ids': tensor([[  101,  1999,  4701,  ...,     0,     0,     0],
        [  101,  2561,  3643,  ...,     0,     0,     0],
        [  101,  1006,  4748,  ...,     0,     0,     0],
        ...,
        [  101,  5678,  1010,  ...,     0,     0,     0],
        [  101,  2033, 20265,  ...,     0,     0,     0],
        [  101,  6983,  2865,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 2, 0, 0, 2, 0, 2, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        0, 2, 2, 0, 1, 0, 0, 2])}
1065
102
1047
2912
1029
3717
2295
1242
2288
2602

Training:  43%|████▎     | 53/122 [00:05<00:06, 11.40it/s]

952
351
518
3819
3039
650
2752
1235
2600
3447
3190
3533
438
3644
1965
1574
294
1977
1929
3257
1023
2865
{'input_ids': tensor([[  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  2057,  3288,  ...,     0,     0,     0],
        [  101,  1996,  3189,  ...,     0,     0,     0],
        ...,
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101, 11281, 18033,  ...,     0,     0,     0],
        [  101, 10958, 13210,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 0, 0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 1, 0, 1])}
3186
3280
2527
923
1726
3619
1482
2979
1494
622
1171
2209
328
3318
2191
2372
3350
29
1616
547
2631
449
2311
19
2972
2965
2512
971
3778
1410
2093
1340
{'input_ids': tensor([[  101, 10958, 10421,  ...,     0,     0,     0],
        [  101, 22098,  4149,  ...,     0,     0,     0],
        [  101,  1996,  4132,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2047,  ...,     0,     0,     0],
        [  101,  1996,  2088,  ...,     0,     0,     0],
        [  101,  2036,  1996,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 0,
        2, 1, 1, 0, 2, 1, 0, 0])}
3381
65
2266
1227
25
3834
2714
793
3227
2789
3010
1810
3596
499
733
2126
2292
1091
2850
1220
114
1902
1887
988
941

Training:  45%|████▌     | 55/122 [00:05<00:05, 11.50it/s]

1090
43
2769
3538
425
860
689
{'input_ids': tensor([[  101,  1036,  1036,  ...,     0,     0,     0],
        [  101, 12316,  2102,  ...,     0,     0,     0],
        [  101, 12436, 14268,  ...,     0,     0,     0],
        ...,
        [  101, 13433, 12541,  ...,     0,     0,     0],
        [  101,  6636, 26557,  ...,     0,     0,     0],
        [  101,  1037,  2334,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 2, 1, 1, 0])}
3710
2141
1808
1185
3617
2012
3134
2301
3650
28
3346
3155
3262
3642
1692
1989
2187
2874
2001
1518
3314
3697
1002
2718
3803
3872
1544
3638
599
193
1217
2786
{'input_ids': tensor([[  101,  1996,  2034,  ...,     0,     0,     0],
        [  101, 17768, 21823,  ...,     0,     0,     0],
        [  101, 13433, 12541,  ...,     0,     0,     0],
        ...,
        [  101,  1996, 10848,  ...,     0,     0,     0],
        [  101,  3820,  2007,  ...,     0,     0,     0],
        [  101,  1996,  2060,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 2, 0, 1,
        0, 1, 0, 2, 0, 0, 1, 0])}
1247
1915
374
3790
3110
1768
597
2799
3486
3547
2640
2484
3452
2365
977
42
3791
255
2433
488
3396
3759
3764
418
1906
2970
3237
1968
3688
67
1690
3777
{'input_ids': tensor([[ 101, 1037, 2254,  ...,    0,    0,    0],
        [ 101, 6983, 8783,  ...,    0,    0,    0],
        [ 101, 2009, 2038,  ...,    0,    0,    0],
        ...,
        [ 101, 5658, 4341,  ...,    0,    0,    0],
        [ 101, 1996, 4118,  ...,    0,    0,    0],
        [ 101, 2027, 2119,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 0, 1, 1, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 0])}
2175
711
2896
3483
777
1740
2303
954
126
398
1852
662
1441
2905
856
3455
2924
158
3707
3112
2959
2119
292
384
3275
1100
1509
3104
3756

Training:  48%|████▊     | 59/122 [00:05<00:05, 12.20it/s]

2593
1051
2717
{'input_ids': tensor([[ 101, 2076, 1996,  ...,    0,    0,    0],
        [ 101, 2446, 4012,  ...,    0,    0,    0],
        [ 101, 2061, 2720,  ...,    0,    0,    0],
        ...,
        [ 101, 1999, 9838,  ...,    0,    0,    0],
        [ 101, 1999, 2289,  ...,    0,    0,    0],
        [ 101, 2429, 2000,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 0, 1, 0, 0])}
272
741
2860
3591
3242
3631
3272
70
1920
495
3170
2124
965
534
3377
2143
116
2077
2501
71
1978
3513
1691
2748
900
3733
562
1521
2380
879
2739
3636
{'input_ids': tensor([[  101,  2241,  2006,  ...,     0,     0,     0],
        [  101,  4754, 15333,  ...,     0,     0,     0],
        [  101,  6983, 24797,  ...,     0,     0,     0],
        ...,
        [  101,  4518,  3863,  ...,     0,     0,     0],
        [  101,  1996,  3688,  ...,     0,     0,     0],
        [  101, 14420,  3472,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 1, 2, 0, 1, 0, 0, 2, 2, 0, 0, 0,
        0, 0, 2, 2, 0, 0, 0, 0])}
314
2917
2000
949
177
1681
1446
2008
1629
2235
3771
866
3580
1954
2139
2393
335
2430
1236
1436
1375
3590
385
1750
2696
2864
884
1150
205
2300
1805
2955
{'input_ids': tensor([[  101,  1999,  2230,  ...,     0,     0,     0],
        [  101, 10958, 13210,  ...,     0,     0,     0],
        [  101, 26374,  2050,  ...,     0,     0,     0],
        ...,
        [  101, 21287,  1010,  ...,     0,     0,     0],
        [  101,  1996,  3803,  ...,     0,     0,     0],
        [  101,  1996,  2047,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0,
        0, 1, 0, 1, 0, 0, 1, 0])}
3321
3734
3670
129
3210
2396
3532
1757
2530

Training:  50%|█████     | 61/122 [00:05<00:05, 12.08it/s]

3285
863
1234
284
3864
3008
3525
2768
1485
818
2548
1785
1208
79
801
1351
3689
1809
2792
220
1082
3427
701
{'input_ids': tensor([[  101,  5761,  2097,  ...,     0,     0,     0],
        [  101, 12436,  8663,  ...,     0,     0,     0],
        [  101,  2002,  5078,  ...,     0,     0,     0],
        ...,
        [  101,  3653,  1011,  ...,     0,     0,     0],
        [  101,  2012,  1996,  ...,     0,     0,     0],
        [  101,  1996, 11943,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 1])}
3277
1324
2142
2773
3342
1035
2089
3835
558
2080
3459
2037
2939
3444
3047
2604
3829
3152
2284
2146
144
2413
3013
2566
920
1400
3600
821
93
2657
278
2481
{'input_ids': tensor([[ 101, 1996, 2274,  ...,    0,    0,    0],
        [ 101, 2007, 1996,  ...,    0,    0,    0],
        [ 101, 1996, 3189,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 2311,  ...,    0,    0,    0],
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 5618, 2005,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 1])}
2713
2217
1952
2500
2118
3512
714
466
2497
645
2168
3871
1526
3477
3417
2843
3336

Training:  52%|█████▏    | 63/122 [00:06<00:05, 11.10it/s]

2179
1672
2735
800
1645
3523
3646
537
2859
2034
2675
1680
1296
2734
975
{'input_ids': tensor([[  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  2166, 13334,  ...,     0,     0,     0],
        [  101,  2000,  6011,  ...,     0,     0,     0],
        ...,
        [  101, 27523,  2361,  ...,     0,     0,     0],
        [  101, 10556,  6968,  ...,     0,     0,     0],
        [  101, 13859,  3006,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0])}
409
184
1052
1899
1260
337
2321
2898
404
1155
620
175
2428
2227
311
2810
1677
986
712
2325
3106
3567
807
1646
1251
1937
1811
1903
3024
208
3552
3368
{'input_ids': tensor([[ 101, 2676, 2254,  ...,    0,    0,    0],
        [ 101, 1999, 2244,  ...,    0,    0,    0],
        [ 101, 1999, 1996,  ...,    0,    0,    0],
        ...,
        [ 101, 1055, 1004,  ...,    0,    0,    0],
        [ 101, 2004, 6873,  ...,    0,    0,    0],
        [ 101, 1996, 8311,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 2, 0, 1, 1, 1, 2, 0, 0, 0, 0, 1,
        2, 0, 0, 2, 0, 0, 1, 1])}
3383
361
1996
3330
2771
3332
1640
3045
452
3240
747
3443
686
648
743

Training:  53%|█████▎    | 65/122 [00:06<00:05, 10.77it/s]

30
672
3858
3675
820
845
3680
1449
302
3014
649
3051
2190
1601
2845
1116
3780
{'input_ids': tensor([[ 101, 1036, 1036,  ...,    0,    0,    0],
        [ 101, 1996, 2177,  ...,    0,    0,    0],
        [ 101, 2004, 1037,  ...,    0,    0,    0],
        ...,
        [ 101, 6983, 4684,  ...,    0,    0,    0],
        [ 101, 1996, 5416,  ...,    0,    0,    0],
        [ 101, 4583, 3667,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 2, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0,
        0, 0, 0, 2, 0, 1, 0, 2])}
778
421
3588
1279
516
2509
2419
1643
2695
1665
1506
510
2199
3121
3255
2113
2728
2927
49
2936
2064
1864
1777
2127
212
666
2225
774
897
45
343
803
{'input_ids': tensor([[  101, 12297, 29109,  ...,     0,     0,     0],
        [  101,  3449, 19800,  ...,     0,     0,     0],
        [  101,  1037,  2261,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2326,  ...,     0,     0,     0],
        [  101,  4082,  5618,  ...,     0,     0,     0],
        [  101,  1996, 18007,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
        2, 0, 2, 1, 0, 1, 2, 0])}
1425
3281
3849
2988
3498
2022
3706
341
3329
2630
1418
1705
1552
1505
1720
2578
1104
553
1078
647
3386
722

Training:  55%|█████▍    | 67/122 [00:06<00:05, 10.75it/s]

1771
2493
663
1581
1654
3863
1134
3811
627
3230
{'input_ids': tensor([[  101,  2414,  3006,  ...,     0,     0,     0],
        [  101,  2603,  2258,  ...,     0,     0,     0],
        [  101,  1037,  4121,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2088,  ...,     0,     0,     0],
        [  101,  3531, 12367,  ...,     0,     0,     0],
        [  101,  6983, 12849,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 2, 0, 1, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0])}
3825
1130
2456
812
358
2149
2054
1686
1440
1641
967
3695
2903
791
1038
3428
3735
904
635
2628
2904
836
3441
444
1945
2134
989
3868
746
3180
2580
2832
{'input_ids': tensor([[  101,  1996,  4189,  ...,     0,     0,     0],
        [  101,  4092,  2000,  ...,     0,     0,     0],
        [  101,  4157,  2097,  ...,     0,     0,     0],
        ...,
        [  101,  2057,  3749,  ...,     0,     0,     0],
        [  101, 10731, 20939,  ...,     0,     0,     0],
        [  101,  3158, 28006,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 0, 0, 1, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 2])}
1553
1282
1305
3423
1648
529
1103
3351
1196
1421
3628
3245
2644
947
1612
423
2876
864
2597
888
1466
1678
1626
3385
3108

Training:  57%|█████▋    | 69/122 [00:06<00:05, 10.35it/s]

958
344
3761
2839
1912
1867
2249
{'input_ids': tensor([[  101,  1996,  3206,  ...,     0,     0,     0],
        [  101, 13672,  2700,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        ...,
        [  101, 24098,  1010,  ...,     0,     0,     0],
        [  101,  5848,  2819,  ...,     0,     0,     0],
        [  101,  4555,  3815,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 1, 2, 2, 1, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 2, 1, 0, 2, 0,
        2, 1, 0, 2, 0, 1, 1, 0])}
996
3034
3046
214
1312
331
3489
3201
3614
1536
1299
1096
1956
3577
1953
1713
3056
3682
3572
2204
1112
388
375
345
411
842
925
3677
3608
3869
3023
982
{'input_ids': tensor([[ 101, 1037, 1012,  ...,    0,    0,    0],
        [ 101, 2426, 1996,  ...,    0,    0,    0],
        [ 101, 2720, 1012,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 2311,  ...,    0,    0,    0],
        [ 101, 2002, 2179,  ...,    0,    0,    0],
        [ 101, 1996, 2047,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 1, 0, 0, 2, 0, 0, 0])}
1846
3291
579
1022
827
3480
1069
1969
544
2290
677
1976
687
2478
468
664
2816
3838
1578
1861
611
3488
3107
3655
2921
3401
3144
2397

Training:  58%|█████▊    | 71/122 [00:06<00:04, 10.43it/s]

739
2807
2400
3323
{'input_ids': tensor([[ 101, 2174, 1010,  ...,    0,    0,    0],
        [ 101, 1036, 1036,  ...,    0,    0,    0],
        [ 101, 1996, 4405,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 2358, 6525,  ...,    0,    0,    0],
        [ 101, 1996, 2193,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 2])}
3551
2662
2219
2495
478
2521
726
1778
3744
3740
3704
2961
2131
3821
1311
1548
140
3307
3410
2251
1704
3413
3380
1498
2382
2244
932
148
3851
2002
2220
725
{'input_ids': tensor([[  101,  1996,  3813,  ...,     0,     0,     0],
        [  101,  1999,  2804,  ...,     0,     0,     0],
        [  101,  2036,  1999,  ...,     0,     0,     0],
        ...,
        [  101,  1999,  2289,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101, 13433,  2232,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        1, 0, 2, 0, 0, 0, 2, 0])}
1392
2869
3595
3507
3339
862
1683
3196
3641
3205
128
2900
1611
2985
713
2193
3853
1715
3322
1259
182
1422
1972
2439
2427
3843
2685
1866
839
710
31
3711
{'input_ids': tensor([[  101,  2030, 20282,  ...,     0,     0,     0],
        [  101,  8511,  4910,  ...,     0,     0,     0],
        [  101,  1996,  2373,  ...,     0,     0,     0],
        ...,
        [  101,  1996, 17396,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101,  2034,  4284,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 1, 1])}
1575
1459
2229
91
1284
2594
2742
1638
515

Training:  60%|█████▉    | 73/122 [00:06<00:04, 11.08it/s]

3408
3379
630
3609
2082
1473
53
413
164
3468
3298
598
394
525
1301
2109
1676
132
2436
3758
3574
721
1198
{'input_ids': tensor([[  101,  1999, 14037,  ...,     0,     0,     0],
        [  101,  1011,  5356,  ...,     0,     0,     0],
        [  101,  2709,  2006,  ...,     0,     0,     0],
        ...,
        [  101,  1058, 25311,  ...,     0,     0,     0],
        [  101,  5929,  4677,  ...,     0,     0,     0],
        [  101,  1996,  3206,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 2, 1, 1, 1, 0, 2, 2, 1,
        0, 1, 0, 1, 0, 0, 1, 1])}
2404
3640
51
342
3226
1249
3406
2787
667
3241
157
481
3249
2744
1350
119
2627
3148
2747
233
1775
2991
2664
3774
3664
770
3067
1448
877
427
2532
1790
{'input_ids': tensor([[  101,  1996,  3206,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101, 10329,  1010,  ...,     0,     0,     0],
        ...,
        [  101, 12331, 21358,  ...,     0,     0,     0],
        [  101,  4684,  3042,  ...,     0,     0,     0],
        [  101,  2429,  2000,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 1, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 2, 0, 2, 0, 1, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 1, 1])}
859
1802
3091
1292
3081
1728
3135
3568
213
531
3364
2092

Training:  63%|██████▎   | 77/122 [00:07<00:03, 11.43it/s]

3287
1477
217
1261
1264
1501
924
826
708
1739
2344
852
3484
2067
2152
610
3295
3399
2619
191
{'input_ids': tensor([[  101,  1999,  2804,  ...,     0,     0,     0],
        [  101,  1996,  6670,  ...,     0,     0,     0],
        [  101,  1048,  1004,  ...,     0,     0,     0],
        ...,
        [  101,  4101, 21423,  ...,     0,     0,     0],
        [  101,  1996, 20138,  ...,     0,     0,     0],
        [  101,  3988,  4358,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0,
        1, 1, 0, 1, 2, 0, 1, 0])}
2836
1747
3830
1893
551
1152
1108
2256
1987
1456
951
1285
2280
636
1569
2468
52
3335
1408
1865
1843
3032
9
2194
1443
3553
432
2925
308
829
1328
2354
{'input_ids': tensor([[  101,  1996,  3820,  ...,     0,     0,     0],
        [  101,  1996,  5761,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        ...,
        [  101,  5741,  3913,  ...,     0,     0,     0],
        [  101,  5658,  4341,  ...,     0,     0,     0],
        [  101,  6636, 26557,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 2, 0, 1, 2, 2, 0, 1])}
1606
2153
3867
3799
2341
3168
230
1184
2422
94
1531
885
615
1200
646
2157
942
962
2861
1767
1895
1495
1513
850
517
2496
3059
2699
2041
751
3763
47
{'input_ids': tensor([[  101, 12849,  2638,  ...,     0,     0,     0],
        [  101,  1996,  4545,  ...,     0,     0,     0],
        [  101,  1996,  4189,  ...,     0,     0,     0],
        ...,
        [  101,  2009,  5748,  ...,     0,     0,     0],
        [  101,  2000,  5333,  ...,     0,     0,     0],
        [  101,  3431,  2000,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2,
        1, 1, 1, 0, 1, 0, 0, 0])}
3725
1908
21
1858
3727
3837
437
637
1761

Training:  65%|██████▍   | 79/122 [00:07<00:03, 11.34it/s]

1352
2424
3798
2809
3773
1209
3515
2615
3874
3487
3395
1404
1759
567
3132
2236
3040
3648
2049
2887
274
1661
1701
{'input_ids': tensor([[  101,  2007,  1996,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0],
        [  101,  4467,  3330,  ...,     0,     0,     0],
        ...,
        [  101,  1037, 14492,  ...,     0,     0,     0],
        [  101, 12849,  2638,  ...,     0,     0,     0],
        [  101,  2057,  3749,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 2,
        0, 0, 2, 1, 0, 0, 0, 0])}
2818
3775
2392
59
2885
658
2526
327
1417
3126
2243
2003
2206
3425
1941
2357
792
2465
1543
673
3133
3610
875
586
3496
90
1639
3584
1620
2514
3676
524
{'input_ids': tensor([[  101, 14285, 11864,  ...,     0,     0,     0],
        [  101,  2011, 14972,  ...,     0,     0,     0],
        [  101,  1996,  9313,  ...,     0,     0,     0],
        ...,
        [  101,  6983, 18762,  ...,     0,     0,     0],
        [  101,  4628,  6702,  ...,     0,     0,     0],
        [  101,  6983, 10514,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 1, 0, 2, 1, 2])}
2954
2565
150
3678
1018
614
2053
922
1963
2541
2618
1357
3360
2368
1011
403
2894
2050
2081
3549
76
3183

Training:  66%|██████▋   | 81/122 [00:07<00:03, 11.85it/s]

2174
3797
2412
41
145
1458
33
431
2203
1572
{'input_ids': tensor([[  101,  5356,  4834,  ...,     0,     0,     0],
        [  101,  2720,  8670,  ...,     0,     0,     0],
        [  101,  1996,  3206,  ...,     0,     0,     0],
        ...,
        [  101,  5658,  4341,  ...,     0,     0,     0],
        [  101,  1996, 14591,  ...,     0,     0,     0],
        [  101,  1997,  1996,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 1, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 0])}
346
1571
1992
2880
3325
3724
1181
1183
235
505
3018
376
3269
2178
3716
1656
2552
250
938
1733
251
2090
2506
61
2429
3398
3075
1710
1491
1487
2011
754
{'input_ids': tensor([[  101,  4031, 23534,  ...,     0,     0,     0],
        [  101,  2797, 10067,  ...,     0,     0,     0],
        [  101,  2206,  2049,  ...,     0,     0,     0],
        ...,
        [  101, 10514, 20936,  ...,     0,     0,     0],
        [  101,  1999,  2289,  ...,     0,     0,     0],
        [  101,  2028,  1997,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 2, 2, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 1,
        0, 0, 0, 2, 0, 1, 0, 0])}
1904
936
3516
127
2881
1123
2386
3491
878
1613
2883
2648
2273
3437
2997
2736
2159
2665
1997
2132
2882
735
1385
2733
275
927
3612
2252
3607
523
3726
768
{'input_ids': tensor([[  101, 12331, 21358,  ...,     0,     0,     0],
        [  101,  2474,  9189,  ...,     0,     0,     0],
        [  101, 10093,  7951,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2449,  ...,     0,     0,     0],
        [  101,  7327,  2099,  ...,     0,     0,     0],
        [  101,  2429,  2000,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 1, 2, 0, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0])}
858
1419
3449
783
203
350
2440
248
2216
2633

Training:  68%|██████▊   | 83/122 [00:07<00:03, 11.05it/s]

2553
2137
1139
2793
1927
1528
1141
1028
3119
3088
1394
462
3576
3700
1585
3163
2083
1523
2977
3524
1653
3594
{'input_ids': tensor([[ 101, 2012, 1996,  ...,    0,    0,    0],
        [ 101, 1996, 3745,  ...,    0,    0,    0],
        [ 101, 2004, 1037,  ...,    0,    0,    0],
        ...,
        [ 101, 9946, 1004,  ...,    0,    0,    0],
        [ 101, 6983, 3221,  ...,    0,    0,    0],
        [ 101, 1996, 3643,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
        0, 0, 1, 2, 0, 0, 0, 0])}
401
2470
400
3012
1399
2981
2616
2047
1272
2539
1558
2726
1664
805
2808
262
3776
3712
252
2833
440
2476
3743
1032
120
467
861
2502
2379
461
2652
1177
{'input_ids': tensor([[ 101, 4341, 2031,  ...,    0,    0,    0],
        [ 101, 1996, 8875,  ...,    0,    0,    0],
        [ 101, 2060, 2167,  ...,    0,    0,    0],
        ...,
        [ 101, 2012, 1996,  ...,    0,    0,    0],
        [ 101, 4082, 5618,  ...,    0,    0,    0],
        [ 101, 1996, 3643,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 0, 1, 1, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2,
        0, 2, 0, 1, 1, 2, 2, 0])}
3320
3124
1403
2261
2814
624
1746
1474
443
3404
225
740

Training:  70%|██████▉   | 85/122 [00:08<00:03, 10.59it/s]

2755
3721
3185
2313
870
190
2107
2737
1717
2106
2015
3625
2517
324
3474
2584
1343
1323
3805
1709
{'input_ids': tensor([[  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  6386, 15794,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        ...,
        [  101,  3081,  1996,  ...,     0,     0,     0],
        [  101,  2174,  1010,  ...,     0,     0,     0],
        [  101,  5171,  2203,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 1, 2, 0, 1, 1, 1, 0])}
3254
1079
215
2749
1359
1669
765
843
172
1826
1369
1725
2373
22
2655
1819
2666
420
204
1563
564
764
2276
2104
814
1111
760
325
3478
3752
3859
2712
{'input_ids': tensor([[ 101, 1011, 1996,  ...,    0,    0,    0],
        [ 101, 1996, 6378,  ...,    0,    0,    0],
        [ 101, 1037, 2541,  ...,    0,    0,    0],
        ...,
        [ 101, 2023, 5576,  ...,    0,    0,    0],
        [ 101, 1999, 2023,  ...,    0,    0,    0],
        [ 101, 1996, 7909,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0, 0, 1, 1, 2,
        0, 2, 0, 0, 0, 0, 2, 2])}
653

Training:  73%|███████▎  | 89/122 [00:08<00:02, 11.63it/s]

2120
2667
705
616
3416
1012
2232
698
3356
835
458
0
2346
943
445
356
912
3481
769
1433
1256
2115
2042
2445
2025
201
2614
260
2420
2788
173
{'input_ids': tensor([[  101, 12594,  2012,  ...,     0,     0,     0],
        [  101,  5495,  3406,  ...,     0,     0,     0],
        [  101,  2122, 10995,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  2070,  1017,  ...,     0,     0,     0],
        [  101,  3081,  1996,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1,
        0, 1, 2, 2, 0, 0, 0, 0])}
3643
3141
1874
2855
1812
485
1205
1191
2328
1832
596
1919
917
2518
2721
970
1188
3573
578
3431
1966
291
3211
3504
2224
117
729
2226
2929
955
1230
976
{'input_ids': tensor([[  101,  2720, 11382,  ...,     0,     0,     0],
        [  101, 17710, 21590,  ...,     0,     0,     0],
        [  101,  2009,  3310,  ...,     0,     0,     0],
        ...,
        [  101,  2634,  1005,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  6983,  3780,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
        1, 0, 1, 2, 0, 1, 0, 0])}
2706
459
2691
3559
3093
3420
3407
2162
1947
258
2525
2957
75
3861
2605
1524
1942
3316
2998
2275
1268
3166
3382
891
2825
1555
330
873
1172
285
430
3374
{'input_ids': tensor([[  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  2007,  2023,  ...,     0,     0,     0],
        [  101,  1050,  1011,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  3484,  ...,     0,     0,     0],
        [  101,  6983, 27902,  ...,     0,     0,     0],
        [  101,  1996, 25249,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 2, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 2, 2, 0])}
560
2889
592
2962
1329

Training:  75%|███████▍  | 91/122 [00:08<00:02, 11.54it/s]

3140
2856
2846
180
2076
2573
533
2636
2813
2766
2863
2387
3653
1580
3043
983
2784
2570
3476
3225
1940
1797
2184
2177
959
772
2760
{'input_ids': tensor([[ 101, 9308, 1010,  ...,    0,    0,    0],
        [ 101, 2037, 5378,  ...,    0,    0,    0],
        [ 101, 1036, 1036,  ...,    0,    0,    0],
        ...,
        [ 101, 1006, 4748,  ...,    0,    0,    0],
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 1996, 3189,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0,
        0, 0, 2, 0, 0, 0, 1, 0])}
3208
475
2121
3149
915
1250
259
2878
2150
2173
1863
606
3785
3718
718
1622
3160
1149
1225
226
898
2144
2873
2824
416
1958
3031
1592
692
2480
1984
3691
{'input_ids': tensor([[  101, 19330,  3669,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  4117,  5658,  ...,     0,     0,     0],
        ...,
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  9089,  2063,  ...,     0,     0,     0],
        [  101,  1996,  2971,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1,
        0, 0, 0, 1, 0, 1, 0, 1])}
3035
3055
199
3228
424
1516

Training:  76%|███████▌  | 93/122 [00:08<00:02, 10.90it/s]

2335
2434
3002
1213
1273
2410
1962
659
1921
3729
678
2416
1816
80
3845
773
155
1193
2914
3236
3169
3215
1201
1128
1326
3338
{'input_ids': tensor([[  101, 11605,  6655,  ...,     0,     0,     0],
        [  101,  2148,  3790,  ...,     0,     0,     0],
        [  101,  4082,  3279,  ...,     0,     0,     0],
        ...,
        [  101,  2011, 13868,  ...,     0,     0,     0],
        [  101,  1996,  3189,  ...,     0,     0,     0],
        [  101,  1996,  3025,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2,
        0, 1, 0, 1, 0, 1, 0, 0])}
675
2406
2323
2094
1395
1519
171
2110
2610
2779
1719
3850
3440
2535
1815
1087
1115
23
2038
1600
3765
3671
2891
2851
828
1537
1206
1114
1027
1484
2258
1192
{'input_ids': tensor([[  101, 12331,  1010,  ...,     0,     0,     0],
        [  101,  2174,  1010,  ...,     0,     0,     0],
        [  101,  2028,  1997,  ...,     0,     0,     0],
        ...,
        [  101,  3653,  2696,  ...,     0,     0,     0],
        [  101,  1036, 13926,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 0, 0,
        1, 0, 1, 0, 1, 2, 0, 0])}
3037
643
2647
3355
1862
1366
2704
297
993
3585
3826
1210
1173

Training:  78%|███████▊  | 95/122 [00:08<00:02, 11.85it/s]

1730
1388
1625
3042
3789
3622
3469
1016
1670
1030
1772
2692
3629
841
2590
2763
2800
1533
2218
{'input_ids': tensor([[  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  1996, 11529,  ...,     0,     0,     0],
        [  101, 12849,  2638,  ...,     0,     0,     0],
        ...,
        [  101, 12316,  2102,  ...,     0,     0,     0],
        [  101,  3393,  7382,  ...,     0,     0,     0],
        [  101,  1996,  3361,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2, 1, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0,
        0, 0, 0, 0, 0, 0, 0, 0])}
1044
1083
573
2074
1660
758
1245
1582
282
451
2377
3460
2409
899
3674
538
3616
3514
2289
2262
268
1718
1298
3293
1001
3229
3392
2405
1694
3626
853
2155
{'input_ids': tensor([[  101,  5658,  5618,  ...,     0,     0,     0],
        [  101,  2268,  1017,  ...,     0,     0,     0],
        [  101,  1996,  3905,  ...,     0,     0,     0],
        ...,
        [  101,  2104,  1996,  ...,     0,     0,     0],
        [  101,  4087, 20390,  ...,     0,     0,     0],
        [  101, 27424,  6673,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 2, 0, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 1, 2, 0, 1, 1])}
1674
1025
3118
3456
3741
3016
3270
680
153
2511
1262
74
1413
2693
2609
3058
652
170
2297
1889
3131
496
2088
2890
756
2673
236
134
1182
1917
682
594
{'input_ids': tensor([[  101,  1996,  8172,  ...,     0,     0,     0],
        [  101,  2043,  2330,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0],
        ...,
        [  101,  8991,  3726,  ...,     0,     0,     0],
        [  101,  5796,  2474,  ...,     0,     0,     0],
        [  101,  6983, 19595,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        2, 0, 1, 0, 1, 0, 0, 1])}
3592
2558
3847
2352
785
3142
3537
1871
2811
448
1356
3458

Training:  80%|███████▉  | 97/122 [00:09<00:02, 11.66it/s]

1595
1745
1158
2944
118
2899
1233
2659
2658
543
2213
2828
456
3521
1109
3506
2645
2523
656
2345
{'input_ids': tensor([[  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  1996,  5494,  ...,     0,     0,     0],
        [  101,  6983, 13594,  ...,     0,     0,     0],
        ...,
        [  101,  3316, 16330,  ...,     0,     0,     0],
        [  101,  2128,  1011,  ...,     0,     0,     0],
        [  101,  3465, 10995,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 2, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 1])}
3583
2052
209
2026
469
3508
3264
1702
287
3781
2915
3645
3562
3367
2531
1926
3779
238
113
1743
1480
626
3204
1344
2277
1178
1054
1102
2457
2472
231
1827
{'input_ids': tensor([[  101,  2066,  2035,  ...,     0,     0,     0],
        [  101,  7297,  1010,  ...,     0,     0,     0],
        [  101,  1996, 24081,  ...,     0,     0,     0],
        ...,
        [  101,  1996, 23362,  ...,     0,     0,     0],
        [  101,  5841,  2097,  ...,     0,     0,     0],
        [  101,  1041,  1005,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 2, 0, 0, 1, 2, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 1, 0, 1, 0])}
97
3813
365
1302
728
2973
748
397
1803
1644
2371
3424
2715
3415
3094
2364
1698
2947
2926
1517
2868
1542

Training:  83%|████████▎ | 101/122 [00:09<00:01, 11.56it/s]

571
3061
15
3138
1499
1724
2934
3485
183
707
{'input_ids': tensor([[  101,  1996,  6903,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  5495,  3406,  ...,     0,     0,     0],
        ...,
        [  101,  1999, 10388,  ...,     0,     0,     0],
        [  101,  1996,  7375,  ...,     0,     0,     0],
        [  101,  2044,  1996,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 0, 0])}
3526
465
956
3492
3216
520
66
3369
1358
393
1019
323
554
454
176
1407
3795
362
1800
995
3159
929
1944
3397
2163
1451
2797
2857
2070
2298
2366
3557
{'input_ids': tensor([[  101,  1996,  6614,  ...,     0,     0,     0],
        [  101,  1996,  3869,  ...,     0,     0,     0],
        [  101,  2144, 12149,  ...,     0,     0,     0],
        ...,
        [  101,  1036,  1036,  ...,     0,     0,     0],
        [  101,  1996,  5658,  ...,     0,     0,     0],
        [  101, 20996,  2232,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
        2, 0, 1, 0, 0, 1, 0, 0])}
3535
2577
62
3434
1427
2246
185
2099
3654
1980
625
546
907
2661
221
1807
3731
2777
1174
1712
3840
2009
3243
103
2598
264
1048
2383
631
276
883
1781
{'input_ids': tensor([[  101, 15253, 11475,  ...,     0,     0,     0],
        [  101,  8947,  1011,  ...,     0,     0,     0],
        [  101,  1996,  3408,  ...,     0,     0,     0],
        ...,
        [  101, 20383,  2005,  ...,     0,     0,     0],
        [  101,  1996,  3532,  ...,     0,     0,     0],
        [  101,  1037,  2561,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 2, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 1,
        0, 0, 0, 0, 2, 1, 2, 2])}
550
671
111
2339
1341
3810
1760
2467
2646

Training:  84%|████████▍ | 103/122 [00:09<00:01, 11.68it/s]

1470
1651
3448
3692
3461
2623
1591
473
894
556
2312
1
2688
815
3390
2960
641
476
3366
2125
681
2274
3177
{'input_ids': tensor([[  101,  2747,  1996,  ...,     0,     0,     0],
        [  101,  4082,  5618,  ...,     0,     0,     0],
        [  101,  1036,  1036,  ...,     0,     0,     0],
        ...,
        [  101,  5222,  5818,  ...,     0,     0,     0],
        [  101,  1999,  2561,  ...,     0,     0,     0],
        [  101, 18347, 15687,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 2,
        2, 1, 1, 0, 0, 0, 0, 0])}
848
2278
500
3358
3659
1372
2941
3624
3684
1529
3663
2995
3467
1098
2455
3536
1957
1333
2164
1080
522
1794
699
1468
2731
2871
690
1013
3796
3087
1170
1455
{'input_ids': tensor([[  101,  6983, 23262,  ...,     0,     0,     0],
        [  101,  6636, 26557,  ...,     0,     0,     0],
        [  101,  6983, 13773,  ...,     0,     0,     0],
        ...,
        [  101,  2041, 12184,  ...,     0,     0,     0],
        [  101,  1996,  3653,  ...,     0,     0,     0],
        [  101,  2009,  2036,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 1, 1, 0])}
1609
2716
1281
2679
868
281
2827
1313
1472
1721
3832
408
2774
2066
2158
2299
340
3746
657
1062
2048
644
3313
2348
2171
2214
1673

Training:  86%|████████▌ | 105/122 [00:09<00:01, 11.45it/s]

3405
1286
608
3787
2562
{'input_ids': tensor([[  101,  1999,  1996,  ...,     0,     0,     0],
        [  101,  1996,  3066,  ...,     0,     0,     0],
        [  101,  2588,  2953,  ...,     0,     0,     0],
        ...,
        [  101, 29490,  2038,  ...,     0,     0,     0],
        [  101,  1054,  1004,  ...,     0,     0,     0],
        [  101,  6983, 17710,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 2])}
2694
798
2608
3071
1376
1736
908
998
2751
1287
1110
2205
1623
2095
2508
336
844
1014
2319
283
2964
1496
1991
2281
1949
2254
2033
3206
3668
727
3064
2240
{'input_ids': tensor([[  101,  2429,  2000,  ...,     0,     0,     0],
        [  101,  4526, 19706,  ...,     0,     0,     0],
        [  101,  6983, 20196,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  5416,  ...,     0,     0,     0],
        [  101,  2006,  2254,  ...,     0,     0,     0],
        [  101, 19102,  2747,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 0, 1, 0, 2, 1, 0, 0, 2, 0, 0, 2, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 2])}
2660
1731
674
679
2189
3352
2417
794
3266
668
2671
3194
3788
3828
1711
3161
2820
2524
3766
1169
3833
2426
503
2332
833
1202
1378
2534
3391
895
1097
3841

Training:  89%|████████▉ | 109/122 [00:10<00:01, 12.74it/s]

{'input_ids': tensor([[  101, 22098,  2038,  ...,     0,     0,     0],
        [  101,  9662,  7368,  ...,     0,     0,     0],
        [  101,  1996,  3643,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  1996,  5096,  ...,     0,     0,     0],
        [  101,  1996,  2537,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 0, 2, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 1])}
1636
295
506
2622
618
2172
1435
2756
141
789
389
3223
2112
1657
2922
11
1125
3309
1534
446
1429
3620
3246
2238
1577
3357
3708
1267
3632
2849
3084
414
{'input_ids': tensor([[  101,  3361, 20357,  ...,     0,     0,     0],
        [  101,  1996,  3247,  ...,     0,     0,     0],
        [  101, 18347, 15687,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  4012,  ...,     0,     0,     0],
        [  101,  2009, 13585,  ...,     0,     0,     0],
        [  101,  6983, 13594,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0,
        0, 1, 1, 0, 2, 0, 1, 2])}
3627
498
1232
1503
3403
2201
3421
2893
257
222
3462
3519
670
1153
3418
2343
887
1535
2069
442
3713
383
918
121
1431
1565
2442
2720
3065
1384
745
3027
{'input_ids': tensor([[ 101, 2057, 2191,  ...,    0,    0,    0],
        [ 101, 5618, 2044,  ...,    0,    0,    0],
        [ 101, 2057, 2024,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 3361,  ...,    0,    0,    0],
        [ 101, 1996, 4555,  ...,    0,    0,    0],
        [ 101, 1011, 2039,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
        0, 2, 0, 0, 0, 0, 0, 1])}
3543
1856
1010
1667
2464
1237
1033
832
548
1773
2270
450
312
3028
3178
3800
1444
1167
1897
1339
3175
2872
95
603
3007
3715
3529
3387
628
2361
2398
195
{'input_ids': tensor([[  101,  5495,  3406,  ...,     0,     0,     0],
        [  101, 14841,  9581,  ...,     0,     0,     0],
        [  101,  2429,  2000,  ...,     0,     0,     0],
        ...,
        [  101,  8538, 15092,  ...,     0,     0,     0],
        [  101,  1996,  2827,  ...,     0,     0,     0],
        [  101,  1999,  1996,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 2, 0, 1, 2, 0, 1, 1])}
1447
2116
2337
353
3022
2782

Training:  91%|█████████ | 111/122 [00:10<00:00, 11.99it/s]

202
3244
1922
37
2096
2980
2750
1368
1564
3130
3720
2723
3701
1891
3292
3656
2259
1371
3074
196
2543
1133
660
3184
477
2822
{'input_ids': tensor([[ 101, 1996, 2047,  ...,    0,    0,    0],
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 1996, 2943,  ...,    0,    0,    0],
        ...,
        [ 101, 5658, 4341,  ...,    0,    0,    0],
        [ 101, 2197, 2095,  ...,    0,    0,    0],
        [ 101, 5658, 4341,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 2, 2, 0, 0,
        0, 1, 1, 0, 2, 0, 2, 1])}
123
1749
197
474
702
1338
489
1607
2306
1799
2772
588
1754
1999
1008
2569
3657
1515
1360
2697
3068
3079
3589
1804
3639
1393
2059
198
1380
1143
3063
2101
{'input_ids': tensor([[  101,  2008,  4769,  ...,     0,     0,     0],
        [  101,  2012,  1015,  ...,     0,     0,     0],
        [  101,  9303, 11215,  ...,     0,     0,     0],
        ...,
        [  101,  2197,  2095,  ...,     0,     0,     0],
        [  101,  2206,  1996,  ...,     0,     0,     0],
        [  101,  6983,  7829,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 2, 2, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
        1, 0, 0, 2, 0, 1, 0, 2])}
301
483
1741
2122
3105
1151
3673
3570
665
3365
2086
3426
2844

Training:  93%|█████████▎| 113/122 [00:10<00:00, 11.49it/s]

1254
2432
387
279
3162
3217
3528
931
2202
1796
1752
1633
2315
1070
3430
602
1373
1788
3457
{'input_ids': tensor([[  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  4082,  5618,  ...,     0,     0,     0],
        [  101,  1996,  2561,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  3247,  ...,     0,     0,     0],
        [  101,  1996,  4358,  ...,     0,     0,     0],
        [  101, 12436, 14268,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 2, 0, 0, 1, 0])}
1162
2946
3690
1255
306
1907
2579
3251
2974
3146
3284
3548
795
270
2245
796
914
857
1853
2780
1594
3328
3866
1288
2487
775
1327
1308
2314
8
56
2247
{'input_ids': tensor([[  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  2014,  2197,  ...,     0,     0,     0],
        [  101,  1996,  2712,  ...,     0,     0,     0],
        ...,
        [  101, 20383,  2013,  ...,     0,     0,     0],
        [  101,  1996, 15002,  ...,     0,     0,     0],
        [  101,  3854, 12849,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 2, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 0])}
1829
2381
2482
2908
2745
3550
3807
642
3698
2919
2351
3419
961
1875
371
2958
1058
1353

Training:  94%|█████████▍| 115/122 [00:10<00:00, 11.13it/s]

1031
1675
3157
892
2821
1671
243
101
3669
3750
2994
1998
38
246
{'input_ids': tensor([[ 101, 1996, 1019,  ...,    0,    0,    0],
        [ 101, 1996, 7566,  ...,    0,    0,    0],
        [ 101, 2340, 2257,  ...,    0,    0,    0],
        ...,
        [ 101, 4082, 5618,  ...,    0,    0,    0],
        [ 101, 1996, 7863,  ...,    0,    0,    0],
        [ 101, 1996, 4791,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0, 0,
        0, 0, 0, 2, 0, 2, 1, 0])}
3793
3852
44
1316
1502
3870
1294
266
3359
2309
1195
3120
1873
2483
738
189
2331
300
2796
1160
2674
2310
2039
948
1514
2237
54
504
781
930
3613
935
{'input_ids': tensor([[  101, 24155,  2015,  ...,     0,     0,     0],
        [  101,  1996, 17781,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0],
        ...,
        [  101,  3653,  1011,  ...,     0,     0,     0],
        [  101,  2053,  2062,  ...,     0,     0,     0],
        [  101,  1999,  1053,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 0, 0, 1, 2, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 2])}
1831
706
1695
3633
224
3747
2968
245
2010
3499
539
730
3820
2425
1859
2725
3165
1412
2607
619
3586
1072
703
2207
369
1627
823
960

Training:  96%|█████████▌| 117/122 [00:10<00:00, 10.83it/s]

2072
1099
1481
3685
{'input_ids': tensor([[  101, 29583,  4297,  ...,     0,     0,     0],
        [  101,  2012,  4360,  ...,     0,     0,     0],
        [  101,  2320,  2115,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  4022,  ...,     0,     0,     0],
        [  101,  1011,  1996,  ...,     0,     0,     0],
        [  101,  3224, 10618,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0,
        1, 0, 0, 2, 1, 0, 0, 0])}
1121
1914
715
559
2629
719
3705
2296
3754
557
1881
105
3501
2360
3400
695
2933
782
3571
20
3015
2637
1883
146
7
2019
2910
3540
514
3340
3078
985
{'input_ids': tensor([[  101,  4012, 13876,  ...,     0,     0,     0],
        [  101,  6599,  1999,  ...,     0,     0,     0],
        [  101,  2147,  2006,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2087,  ...,     0,     0,     0],
        [  101,  6983,  8139,  ...,     0,     0,     0],
        [  101, 22563, 21766,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 1])}
3699
2408
1814
3253
1043
581
1297
763
3080
142
1840
3191
1527
210
1396
436
321
3542
1787
2920
2061
1776
1168
3482
1706
669
3198
2435
3344
1017

Training:  98%|█████████▊| 119/122 [00:11<00:00, 10.53it/s]

724
587
{'input_ids': tensor([[  101,  1996,  7848,  ...,     0,     0,     0],
        [  101, 20248,  5054,  ...,     0,     0,     0],
        [  101,  1996, 11817,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2194,  ...,     0,     0,     0],
        [  101,  2009,  2003,  ...,     0,     0,     0],
        [  101,  1996,  2897,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0])}
1362
2907
2353
2690
87
2078
1463
3038
69
508
329
2515
563
2617
1319
1258
2448
816
540
1967
211
1095
3463
2185
2536
186
187
3686
2018
3062
3597
2462
{'input_ids': tensor([[ 101, 2053, 3976,  ...,    0,    0,    0],
        [ 101, 1996, 2194,  ...,    0,    0,    0],
        [ 101, 2007, 2274,  ...,    0,    0,    0],
        ...,
        [ 101, 5454, 2013,  ...,    0,    0,    0],
        [ 101, 2009, 2036,  ...,    0,    0,    0],
        [ 101, 1999, 2258,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 2, 0, 2, 1, 0, 0, 1, 2, 2,
        1, 2, 0, 1, 2, 0, 0, 0])}
1779
3375
332
3522
969
1280
2835
382
3666
3618
1833
580
1983
1960
3123
1762
2520
2282
1993
2182
3289
110
3809
1216
3696
2879
872
1423
267
2672
2023
749

Training: 100%|██████████| 122/122 [00:11<00:00, 10.86it/s]

{'input_ids': tensor([[  101, 10462,  9303,  ...,     0,     0,     0],
        [  101,  2013,  2494,  ...,     0,     0,     0],
        [  101,  1055,  2449,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  3745,  ...,     0,     0,     0],
        [  101,  5082,  2177,  ...,     0,     0,     0],
        [  101,  2429,  2000,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 2, 1,
        0, 0, 0, 0, 0, 0, 1, 1])}
1118
2571
359
3694
166
3143
3806
1916
2575
2971
2901
1077
2415
762
78
2638
1792
3371
1928
1818
3757
305
2181
1050
3294
2293
3587
48
2563
40
950
1003
{'input_ids': tensor([[  101, 19330,  5737,  ...,     0,     0,     0],
        [  101,  9944,  5403,  ...,     0,     0,     0],
        [  101,  1996,  2047,  ...,     0,     0,     0],
        ...,
        [  101,  2104,  1996,  ...,     0,     0,     0],
        [  101,  1996, 13371,  ...,     0,     0,     0],
        [  101,  1996,  2194,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'labels': tensor([1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 1, 0,
        0, 0, 0, 1, 2, 1, 0, 1])}
2269
1263
3783
2730
{'input_ids': tensor([[  101,  1996,  7233,  1997,  5157,  2008,  2318,  2646,  1996,  2203,
          1997,  2268,  1010,  2506,  1999,  2254,  1011,  2233,  2230,  1012,
           102,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  2057,  2298,  2830,  2000,  2202,  2112,  1999,  1996,  2925,
          2458,  1997,  1996,  2194,  1010,  1005,  1005,  2758, 12675, 25640,
          1010,  2343,  1997, 13926,  3367, 20009,  7229,  1012,   102,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  9303, 11215, 24545,  1024,  9303, 11215,  3488,  2000,  5587,
          2062,  7599,  2006,  5847,  2000,  4291,  4290,  1010,  2634,  1998,
          3607,  1012,   102,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0],
        [  101,  1048,  2912,  2497,  1010,  9403,  1999, 11320, 19738,  1010,
          4701,  1010,  2003,  1037,  2152,  1011,  6627,  5471,  2194,  5155,
          9725,  3707, 10848,  3688,  2005,  1996,  3886,  3068,  1012,   102,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'labels': tensor([1, 0, 1, 0])}